### ISSUE TITLE
API rate limit exceeded for user ID

### ISSUE THREAD

**Issue by snarby2013** [custom-components/hacs#106]
HACS version 0.7

Too many restarts exceeds API rate limit and crashes Home Assistant

custom_components.hacs.aiogithub.AIOGitHubException: API rate limit exceeded for user ID

**Comment by ludeeus** [comment]
Please share the entire startup log

**Comment by snarby2013** [comment]
I dont have it anymore as HA started working once I removed it. I just re-added hacs: and its working now so can't recreate the issue but will try restarting a few times and see if it happens again

**Comment by snarby2013** [comment]
Just restarted 11 times and not an issue so may only be when setting up for the first time

curl -i https://api.github.com/users/snarby2013
HTTP/1.1 200 OK
Date: Sun, 16 Jun 2019 09:19:23 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 1283
Server: GitHub.com
Status: 200 OK
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 49
X-RateLimit-Reset: 1560679645

**Comment by ludeeus** [comment]
I was able to recreate it, will add exceptions to the next version

**Comment by snarby2013** [comment]
ok great, thanks

**Comment by ludeeus** [comment]
Version 0.8.0 has exceptions for this issue.
<https://github.com/custom-components/hacs/releases/tag/0.8.0>
