### ISSUE TITLE
integrations and 2 questions, no issue, 

### ISSUE THREAD

**Issue by IIIdefconIII** [custom-components/hacs#110]
First of al, thank you so much for this plugin, its more then awesome. Whenever i get my payday i donate you some beers! I couldnt get up a better title for this issue/question/

After installing the cards they all say: "you still need to add it to your lovelace configuration ('ui-lovelace.yaml' or the raw UI config editor). "

Some of them have:
```
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
```

others have just the URL without the type:
`  - url: /community_plugin/compact-custom-header/compact-custom-header.js`

I got 2 questions:
1. do we need the type? or can we just use the URL.
2. Where can i create a PR to the ones that have no example, like Plex Recently Added.
I would love to put some time in this for the cards im using and set the example on the pages. But im not sure where to do this.

**Comment by ludeeus** [comment]
I'm not sure if the type is needed, I think there is a default bu unsure what that is.

The type is gathered by parsing the README in the repository for the plugin :)

**Comment by IIIdefconIII** [comment]
> I'm not sure if the type is needed, I think there is a default bu unsure what that is.
> 
> The type is gathered by parsing the README in the repository for the plugin :)

i tested it without type, not working, so f.y.i. yes type is still needit.
