### ISSUE TITLE
Re-structure folder to be able to git clone into custom_components

### ISSUE THREAD

**Issue by shbatm** [custom-components/hacs#116]
**Is your feature request related to a problem? Please describe.**
Current installation method requires downloading each release and unzipping into the custom components folder.

**Describe the solution you'd like**
Restructure the repo's folders such that it can be cloned directly into `custom_components` and that way on a new release, all that is required is a `git pull` in that folder.

**Comment by ludeeus** [comment]
This will break compatibility with itself.
I have updated the git instructions to not create a temp_dir.

**Comment by shbatm** [comment]
Thanks for the consideration. Can you please elaborate on how it breaks compatibility? I didn't notice any issues installing it that way but maybe I'm missing something.

**Comment by ludeeus** [comment]
It uses itself to upgrade, and the purposed change is not compliant with the requirements.
https://custom-components.github.io/hacs/#note-for-integration-developers
