### ISSUE TITLE
URL Leaking

### ISSUE THREAD

**Issue by peternijssen** [custom-components/hacs#124]
## Version of HACS
HACS version: 0.8.0 
Home Assistant version: 0.94.3

## Describe the bug
As a plugin developer, I've noticed that in my insights page on Github, I see a lot of URLs from people's home instances. This probably is due to the fact that people are clicking the "open repository" link and thus sending along the referrer header to Github. 
Securing their home instance, when connected to the web, is the responsibility of the owner, but I thought it might be wise to add things like `rel="noreferrer"` to the URLs going to the outside world or setting the referrer header (https://scotthelme.co.uk/a-new-security-header-referrer-policy/)

Not sure how much control you have over this and how much you find this an issue.

**Comment by ludeeus** [comment]
Thanks for reporting, and please upgrade.


> how much you find this an issue.

Does this answer that? https://github.com/custom-components/hacs/releases/tag/0.8.1 :D
