### ISSUE TITLE
Setting layout issues on  iOS 

### ISSUE THREAD

**Issue by aptonline** [custom-components/hacs#126]
## Version of HACS
0.8.1

## Describe the bug
The layout of the setting within iOS (specifically on an iPhone) is not displaying correctly. Please see image.

## Debug log

No logs to show for this issue.
![70713071-4A4A-4B07-A544-6336D4B6B94D](https://user-images.githubusercontent.com/190136/59720850-c9db3400-9217-11e9-9f08-458b021731f0.png)

**Comment by ludeeus** [comment]
Chrome lied to me... I thought I had fixed that...
![image](https://user-images.githubusercontent.com/15093472/59740543-b4422a80-9268-11e9-94e1-8d15673dae3e.png)

Fix will be in 0.9.0

**Comment by ludeeus** [comment]
Corrected in [0.9.0](https://github.com/custom-components/hacs/releases/0.9.0) 🎉
