### ISSUE TITLE
Monster Card

### ISSUE THREAD

**Issue by h4nc** [custom-components/hacs#131]
That's a quick one

The information in moster card tells you to add:

`  - url: /community_plugin/monster-card/monster-card.js`

what we need is :

```
  - url: /community_plugin/monster-card/monster-card.js
    type: js
```

**Comment by aidbish** [comment]
You will probably find it was due to HACS being unable to determine the type from the repository., it will say to go to the repository itself to check

**Comment by ludeeus** [comment]
It does not tell you anything, it gives a sugestion ;)
That sugestion is based of the README.md in the repository.

As noted by @aidbish if it can not detect it, it will say:
```
HACS could not determine the type of this element, look at the documentation in the repository
```
