### ISSUE TITLE
List view version of Overview page

### ISSUE THREAD

**Issue by jchasey** [custom-components/hacs#133]
First of all fantastic add-on, many thanks for developing.

Would like to suggest a compact view of the components in a list form, one line per plugin/integration.

This would allow at a glance view on a single page rather than having to scroll down to see what is out of date etc.

**Comment by ludeeus** [comment]
In progress.

Overview:
![image](https://user-images.githubusercontent.com/15093472/59785843-2f85f980-92c6-11e9-93e2-2290ebd52468.png)

Store:
![image](https://user-images.githubusercontent.com/15093472/59785855-390f6180-92c6-11e9-8b9a-760c601f943f.png)

**Comment by ludeeus** [comment]
Implemented in [0.9.0](https://github.com/custom-components/hacs/releases/0.9.0) 🎉
