### ISSUE TITLE
add notification to the overview page for update available for HACS component

### ISSUE THREAD

**Issue by finity69x2** [custom-components/hacs#140]
**Is your feature request related to a problem? Please describe.**

nope

**Describe the solution you'd like**

see title. ;)

There should be a box on the overview screen for update notifications like other components instead of in the "settings" area.

**Comment by tomlut** [comment]
I would like to see this too. Yesterday I got a notification (based on the hacs sensor) that an update was available but it took me a while to work out that this was for hacs itself as all my icons on the overview page were green.

**Comment by atomicpapa** [comment]
I also ran into this the first time it happened.  Now, of course, I just head to settings when everything is green on the overview page, but I would think HACS updates deserve a position of prominence on the Overview page.  :-)

**Comment by ludeeus** [comment]
Implemented in [0.9.0](https://github.com/custom-components/hacs/releases/0.9.0) 🎉
