### ISSUE TITLE
Support Integrations with extra files

### ISSUE THREAD

**Issue by tomlut** [custom-components/hacs#143]
**Is your feature request related to a problem? Please describe.**

Example: Bwalarm has files in the `www/panel/` folder. These are not updated when the component updates.

**Describe the solution you'd like**

- **Ideal:** update all the files. 
- **Acceptable:** developer includes a note that some files must be updated manually.
- **Not Acceptable:** blocking the integration

**Describe alternatives you've considered**

Living a hippy lifestyle in a nature commune that shuns technology.

**Additional context**

Repo location: https://github.com/akasma74/Hass-Custom-Alarm

**Comment by ludeeus** [comment]
The developer can place any file under the integration directory, these will be downloaded.
The developer can add notes for the user by using `info.md` <https://custom-components.github.io/hacs/developer/general/#enhance-the-experience>

As for blocking, any repository that the author of will have removed, I will remove.
Same goes if a repository is flagged for being dangerous/stealing data.

> Living a hippy lifestyle in a nature commune that shuns technology.

Would probably solve some things...

As for the repository you have noted here <https://github.com/akasma74/Hass-Custom-Alarm/pull/11>
