### ISSUE TITLE
Use the same scroll bar type as home assistant frontend

### ISSUE THREAD

**Issue by Knapoc** [custom-components/hacs#147]
**Is your feature request related to a problem? Please describe.**
HACS is using a different (thicker) scroll bar compared to the browser default. As a result the UI doesn't look consistent.

**Describe the solution you'd like**
HACS should use the browser's default scroll bar or Home Assistant's CSS-theming.

**Additional context**
HACS scroll bar:
![IMG_3029](https://user-images.githubusercontent.com/21982227/59953968-d1eadc00-9482-11e9-9162-a0d22120e5b3.jpg)

Safari iOS companion app scroll bar:
![IMG_3031](https://user-images.githubusercontent.com/21982227/59954009-01014d80-9483-11e9-86d7-fa7a48dd7298.jpg)

**Comment by ludeeus** [comment]
The one HA uses is _ugly_ so no...
![image](https://user-images.githubusercontent.com/15093472/59954230-fbf0ce00-9483-11e9-9284-b0c1a81d585c.png)

For mobile (atleast iOS) it will use the browser default from 0.9.0

**Comment by Knapoc** [comment]
Gotta agree that the one you just postet doesn't look nice but isn't this a browser issue? As of now I haven't encountered a scroll bar like this.

**Comment by ludeeus** [comment]
Have no idea, I use chrome 🤷‍♂

**Comment by ludeeus** [comment]
Corrected for mobile in [0.9.0](https://github.com/custom-components/hacs/releases/0.9.0) 🎉 
I have no intention of changing this on a desktop device.
