### ISSUE TITLE
Cannot add Life360 custom repo

### ISSUE THREAD

**Issue by ocalvo** [custom-components/hacs#148]
## Version of HACS
HACS version: 0.8.1
Home Assistant version: 0.94.3

## Describe the bug

Cannot add repo: 
https://github.com/pnbruckner/homeassistant-config

Expected:
To list the Life360 integration
Actual:
ArmCrest camera integration is listed/

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
Correct
