### ISSUE TITLE
Being able to clearly see if there is an update

### ISSUE THREAD

**Issue by klaasnicolaas** [custom-components/hacs#15]
**Is your feature request related to a problem? Please describe.**
What I still miss is a slightly clearer recognition of when a component has an update, at the moment this is only visible through a yellow arrow.

**Describe the solution you'd like**
You could solve this by putting components with an update on top in your overview or give the component a different card color.

**Comment by ludeeus** [comment]
@klaasnicolaas @vMeph

Would something like this fit your needs to separate them?

![image](https://user-images.githubusercontent.com/15093472/58824281-fa2daa80-863b-11e9-8edc-87c0f6588eb4.png)
The layout is a result of #40 

White: not installed
Green: Installed (no action required)
Red: Restart pending
Orange: Update pending

**Comment by klaasnicolaas** [comment]
Yeah I like this!

**Comment by ludeeus** [comment]
This was included in the [`0.5.0` release](https://github.com/custom-components/hacs/releases/tag/0.5.0)
