### ISSUE TITLE
Target folder for plugin?

### ISSUE THREAD

**Issue by Tom-ahawk** [custom-components/hacs#151]
Target folder for Hacs plugins?

When installing custom Lovelave cards from the Hacs repository, different cards instruction states the installation folder to be  ".../community_plugin/..."  or «.../community/...".
And when the plugin is installed the folder is created.

Is there a reason for using different target folder, should this be in the same target folder?

**Comment by ludeeus** [comment]
`/community_plugin/` is an endpoint.
`www/community/`  is a directory.

This is not the same thing.

The `/community_plugin/` points to the `www/community/` directory.

**Comment by magiva** [comment]
where is the endpoint defined ? is that within the hacs install ?
i cant get my custom card to be found even though i can see the folder within the community folder

**Comment by Aygotori** [comment]
i have the same problem here... 
can't found any card i install with hacs but i can see the plugins folders in `www/community/` directory
