### ISSUE TITLE
Travis error: "Integration not found: hacs"

### ISSUE THREAD

**Issue by brianhanifin** [custom-components/hacs#158]
## Version of HACS
0.9.0

## Describe the bug
I have Travis setup to test my configuration whenever I sync updates to [my GitHub repository](https://github.com/brianhanifin/Home-Assistant-Config). Travis reports an error "Integration not found: hacs" that I have not been able to find a work around yet.

## Debug log
I will just include the most important snippet below. You can see the full log here:
https://travis-ci.org/brianhanifin/Home-Assistant-Config/jobs/549194787
```text
Failed config
  General Errors: 
    - Integration not found: hacs
```

## Attempt to resolve
I added the [terminal commands](https://custom-components.github.io/hacs/installation/terminal/) to the `before_install:` section of [my .travis.yml](https://github.com/brianhanifin/Home-Assistant-Config/blob/master/.travis.yml) and after a few attempts I got those commands to complete without an error, so I think it is working.

## A potential work-around
I already have a travis_secrets.yaml file that stores a scrubbed copy of my secrets file for testing. I could also setup a travis_configuration.yaml to use as well that is missing the hacs: section. Although I would prefer to not have to maintain another alternate copy of a file.

**Comment by ludeeus** [comment]
This is not an issue with this component.
You can probably try your luck by creating a forum post.

**Comment by johntdyer** [comment]
@brianhanifin  - Did you end up opening a forum post on this ?

**Comment by brianhanifin** [comment]
@johntdyer @luddeus

I just completed my post on the community forum.

https://community.home-assistant.io/t/travis-error-with-hacs-ha-community-store/123161

**Comment by ludeeus** [comment]
In case you are wondering HACS run that test (and others) with a CI.
<https://dev.azure.com/custom-components/hacs/_build>
<https://github.com/custom-components/hacs/tree/next/.pipelines>
