### ISSUE TITLE
Release date in Store list

### ISSUE THREAD

**Issue by woody4165** [custom-components/hacs#169]
Hi

It would be nice to have a release date in the Store list for each of the Integrations/plugins.

It can be helpful, from my side, also to identify new items that otherwise will be difficult to detect.

Thanks

**Comment by ludeeus** [comment]
I guess (hope) that you want new items added to the store to be more visible?

A Release date on that page will never happen.

But _maybe_ something like this?

![image](https://user-images.githubusercontent.com/15093472/60116141-c431a100-9777-11e9-85d7-7c4bf86ec096.png)
![image](https://user-images.githubusercontent.com/15093472/60116353-2ab6bf00-9778-11e9-99d1-1ef8c0016f6f.png)

But what is new?
This release?
Does path 0.0.X releases count as a new release?

**Comment by woody4165** [comment]
The new sign should appear when a new integration or plugin appear in the list to notify it was just added. 
The date was to identify a new release, but you already said that it won't happen. 

Thanks

**Comment by ludeeus** [comment]
/polls "I want this" "I don't want this" "I don't care"

**Comment by DavidFW1960** [comment]
I’d like to see ‘New’ updated us covered anyway by the colour code

**Comment by ludeeus** [comment]
What? 🤔

**Comment by DavidFW1960** [comment]
Bloody auto-correct!

The NEW flag as you suggest above to show a newly added component/card would be a not horrible idea but showing a flag for an updated card is not seeded as the icon on the installed card is a different colour when it is updated anyway....

**Comment by ludeeus** [comment]
I think you need to put down your beer or get a better keyboard app :P

Conclusion?
- Adding a "NEW" badge to new store items that will show until you open the details of that item the first time is OK.
- Adding more to installed items (like update badge) is not needed since the status color icon changes.

Would that be correct?

**Comment by DavidFW1960** [comment]
Yes correct.

**Comment by ludeeus** [comment]
Added in https://github.com/custom-components/hacs/releases/tag/0.10.0

**Comment by trancen** [comment]
How about a updated date?
