### ISSUE TITLE
second HACS system won't load (on same token at first, neither on new token)

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-components/hacs#173]
## Version of HACS

0.9
## Describe the bug
not sure if a bug or user error, but since I couldn't find clues in the docs for setting up HACS on more than 1 system, files here for the time being

## Debug log

```text

Add your logs here.

```

please see https://community.home-assistant.io/t/custom-component-hacs/121727/178?u=mariusthvdb 

bottom line:

I installed HACS  on a second system and it wont load anything, even after a few hours. My first HACS install which had loaded most of the plugins got scrambled after that, and only the install of the custom repositories where left.

Could this be cause by me using the same token....?
Ive created a second token, for the second system. After that, Ive reinstated all plugins on the first system, but the second system still wont do anything.

**Comment by ludeeus** [comment]
Enable debug logging, then restart, then paste the log here.

**Comment by Mariusthvdb** [comment]
there's no log, other then timeouts, and nothing in the HACS panel at all, so no log either.

After enabling the HACS on my second system again, to do as you asked, and post a log, yet again all my plugins were gone on the first system....as are all integrations ....

sorry to say but this is a bit to dangerous for me to be experimenting with setups... hope you enough info to try in your development setting.

Just try a secondary install on another machine, and see what happens.
Sorry if I can't be of more help.

**Comment by ludeeus** [comment]
I have this running on 4 setups without any issue.
Without the (homeassistant) log from your setup, there is nothing I can do.
When your situation changes and you can provide the information needed to debug this feel free to open another issue,

**Comment by Mariusthvdb** [comment]
ok but let me ask, do we need a token per setup?

**Comment by ludeeus** [comment]
You should have that, but not needed, that is just for authentication.
