### ISSUE TITLE
Display Readme on integration/plugin page

### ISSUE THREAD

**Issue by knd775** [custom-components/hacs#175]
**Is your feature request related to a problem? Please describe.**
Having to click through to the repository to learn more about plugins that I may be interested in seems unnecessary.

**Describe the solution you'd like**
I would like for the contents of the plugin's readme to be displayed on the store page when you click on the plugin.

**Describe alternatives you've considered**
This could be hidden by default. This way, the page is still concise, but you could click something like a 'More Info' button that would render the readme.

**Comment by ludeeus** [comment]
The developer can add an "info.md" file to show more info <https://custom-components.github.io/hacs/developer/general/#enhance-the-experience>

> but you could click something like a 'More Info' button that would render the readme.

This would effectively be the same as the "REPOSITORY" button (That also render the README, and give you other info as well.)

**Comment by knd775** [comment]
Thanks. The info.md basically does what I am looking for. Too bad virtually no one seems to be using it.
