### ISSUE TITLE
Query plugin and integrations from github instead of hard code

### ISSUE THREAD

**Issue by ljmerza** [custom-components/hacs#181]
Instead of waiting for an update to HACS to get the latest list of integrations, plugins, etc, we have another repo with just these lists that can be updated seperately to avoid an entire update to HACS just for new addons. HACS can then just query this repo to update it's internal list every 500 minutes or so.

**Comment by ludeeus** [comment]
Another repo would be "too much hassle", I've added a `data` branch for this, will implement it to `0.10.0`

**Comment by ludeeus** [comment]
Added in https://github.com/custom-components/hacs/releases/tag/0.10.0
