### ISSUE TITLE
Unable to load module packaging

### ISSUE THREAD

**Issue by MatthewFlamm** [custom-components/hacs#182]
## Version of HACS

0.10.0b following command line installation instructions.

## Describe the bug
HACS doesn't start.  This is the first time using HACS.  The following lines are in configuration.yaml:

```text
hacs:
  token: !secret hacs_token
```

## Debug log

```text
Unable to import hacs: No module named 'packaging'

```

**Comment by ludeeus** [comment]
Corrected in https://github.com/custom-components/hacs/releases/tag/0.10.0
