### ISSUE TITLE
All instances of "Open a issue" should read "open issue" or "open an issue" for correctness.

### ISSUE THREAD

**Issue by Therkim** [custom-components/hacs#183]
Rather silly issue to open, but I figure that every little helps :)

## Version of HACS
 0.9.0

## Describe the bug
Everywhere "open a issue" is written should read "open issue" or "open an issue".

## Debug log
N/A

![image](https://user-images.githubusercontent.com/34111848/60343885-363efb80-99ad-11e9-82db-fcaa8ee44f2c.png)

![image](https://user-images.githubusercontent.com/34111848/60343928-52429d00-99ad-11e9-8b8d-d6eaf453d0ff.png)

**Comment by ludeeus** [comment]
Please open a PR to correct that! :)

**Comment by Therkim** [comment]
I would if I knew how or where to change it! :)

Sorry to be difficult.

**Comment by ludeeus** [comment]
<https://github.com/custom-components/hacs/blob/next/custom_components/hacs/frontend/views/repository.py>
Click the pencil icon.
Find the text you want to edit
edit that text.
scoll to the bottom of the page.
fill out the "schema", click green buttons :)

**Comment by Therkim** [comment]
Thank you, I'll give it a shot now. Learning something new today! :)
