### ISSUE TITLE
Relocate install, upgrade... Buttons to the top 

### ISSUE THREAD

**Issue by JuanMTech** [custom-components/hacs#193]
When checking any custom components, all buttons to install, upgrade, repository, uninstall are located on the bottom. Some integrations like the **Mini Media Player** have a lot of documentation so you have to scroll all the way to the bottom to install it. 

I would suggest moving the buttons to the top similar to the regular add-on in Hass.io. 

![HACS buttons locationo](https://user-images.githubusercontent.com/23154499/60380221-ec3b3180-9a0f-11e9-84eb-7bcb86eb5d49.png)

**Comment by ludeeus** [comment]
There is a reason I chose to do it this way if the buttons are at the bottom it "forces" the user to "read" potentially important information from the developer.

I'm not saying no, but this change needs consensus from more users/devs before implemented.

**Comment by cdrom1028** [comment]
Please build a poll in the community.home-assistant.io forum to gather consensus for this one way or the other.

**Comment by ludeeus** [comment]
done https://community.home-assistant.io/t/custom-component-hacs/121727/190?u=ludeeus

**Comment by ludeeus** [comment]
![image](https://user-images.githubusercontent.com/15093472/60414207-c2346b80-9bd7-11e9-9154-0424029fdce0.png)

**Comment by ludeeus** [comment]
Implemented in 0.11.0 <https://github.com/custom-components/hacs/releases/tag/0.11.0>
