### ISSUE TITLE
Badges don't load correctly

### ISSUE THREAD

**Issue by r3mcos3** [custom-components/hacs#197]
The badges won't load correctly on Android and on my PC aswell,

They don't load since they are included here are some screenshots. 
![1](https://i.imgur.com/XhxNUyJ.jpg)
![2](https://i.imgur.com/CxylfOt.jpg)

**Comment by ludeeus** [comment]
They load just fine your theme is hiding it the text since you use the same color for `--primary-text-color` and `--primary-color`

**Comment by r3mcos3** [comment]
Sorry for the inconvenient, didn't know that!
