### ISSUE TITLE
Persistent notification

### ISSUE THREAD

**Issue by r3mcos3** [custom-components/hacs#20]
Is it possible to get a persistent notification if there is a component or card has a upgrade?

**Comment by ludeeus** [comment]
No, and that will not be added.

Possible viable options for this will be:

1: Add an endpoint that can return json data with this info (you can then create a rest sensor)
2: Add a sensor with this data.
3: Both?

I will not dictate this, I'll leave it up to the community to decide what they want, @r3mcos3 get your fellow users to chime in on this :)

**Comment by maykar** [comment]
I'd say for sure a sensor would help. The user could then decide to either display it in their frontend, create their own notification card using a conditional card, or even use an automation to use `persistent_notification.create`.

**Comment by aidbish** [comment]
+1 for a sensor

**Comment by Sjeff** [comment]
+1 for a sensor

**Comment by bonzai86** [comment]
+1 for a sensor

**Comment by Chaotic** [comment]
Another +1 for the sensor

**Comment by Bastiencc** [comment]
+1 for a sensor

**Comment by ludeeus** [comment]
Can one of you sensor fanatics open a new FR with what types of data (state + attributes) that you would expect to see? 
When we reach a consensus I'll add it, probably for 0.6.0 :)

**Comment by Bastiencc** [comment]
the aim (for me) is to setup an automation that will send me a telegram message when an update is available

**Comment by ludeeus** [comment]
Closed in favor of #56
