### ISSUE TITLE
Break up INTEGRATIONS and PLUGINS into separate tabs

### ISSUE THREAD

**Issue by cdrom1028** [custom-components/hacs#200]
Since the launch of HACS, there has been an extremely rapid growth to the amount of INTEGRATIONS and PLUGINS added with more to come. Navigation could be improved by breaking out INTEGRATIONS and PLUGINS individually in to separate Tabs. 

![community](https://user-images.githubusercontent.com/12717639/60388177-b2077980-9a7b-11e9-852f-92728db10907.png)

**Comment by ludeeus** [comment]
You are aware that it's no longer _just_ integrations and plugins?

**Comment by cdrom1028** [comment]
> You are aware that it's no longer _just_ integrations and plugins?

Even more reason to break things out a little bit. HACS is really a game changer for extending the functionality to Home Assistant. One stop shop for adding enhancements, customization tools, and integrating services.

**Comment by ludeeus** [comment]
![image](https://user-images.githubusercontent.com/15093472/60399682-aa71ce80-9b68-11e9-9282-dd4770b0a350.png)

This does not sit well with me... it's even worse on small screens.

A middle ground would be a dropdown menu.

**Comment by ludeeus** [comment]
![image](https://user-images.githubusercontent.com/15093472/60414143-9913db00-9bd7-11e9-9b5c-e7056e7bad7f.png)

**Comment by JuanMTech** [comment]
A dropdown menu would work inside the Store tab. However, I don't see it needed yet until the store has a lot more options available. Right now using the search bar is pretty fast... Just my 2 cents.

**Comment by ludeeus** [comment]
A dropdown would be instead of the "button" named "store" now.

But I agree, for now, the search is good enough :)

**Comment by JuanMTech** [comment]
How about inside the store tab? When open, you have access to everything but then if you want to filter a specific section, you can just select it from a dropdown. It might work and look better.

**Comment by ludeeus** [comment]
Then you are already in the store, it has generated all items and loaded the page, at that point, it's much faster to scroll and/or search, then to do a selection and rebuild the page.

**Comment by JuanMTech** [comment]
> Then you are already in the store, it has generated all items and loaded the page

Right, so the user can choose if they want to just go through the whole list or filter their selection. 

> at that point, it's much faster to scroll and/or search, then to do a selection and rebuild the page.

Doing a search would definitely be faster "if" you know the exact name for what you are looking for. Scrolling, not really in the future when you have over 100 (hopefully) items in there.

**Comment by cdrom1028** [comment]
> A dropdown would be instead of the "button" named "store" now.
> But I agree, for now, the search is good enough :)

As we sit today, I feel as if search is fine but, as Juan states 

> Doing a search would definitely be faster "if" you know the exact name for what you are looking for. Scrolling, not really in the future when you have over 100 (hopefully) items in there.

A dropdown does make a lot of sense as the other elements get added in making the UI experience stay consistent. But I am not sure how many people are adding heavy modifications to their home assistant system on a "small screen". I know I wont be doing that.

**Comment by gadgetchnnel** [comment]
I was thinking about this, and wondered whether one way of doing this might to be to allow collapsing of the different sections on the Store page? The sections could either default to expanded (so you would click on a header to collapse that section if you are not interested in it) or collapsed (so you would click on the header you want to expand that section.

**Comment by capstan1** [comment]
> ![image](https://user-images.githubusercontent.com/15093472/60399682-aa71ce80-9b68-11e9-9282-dd4770b0a350.png)
> 
> This does not sit well with me... it's even worse on small screens.
> 
> A middle ground would be a dropdown menu.

As an answer to your mockup: from a users perspective it rather should be like this imho:
![mockup](https://user-images.githubusercontent.com/17147867/61691484-f6f59780-ad2b-11e9-9425-5b7a79ad7c34.jpg)

The "overview" is one heading, store and settings are others. The categories aren't more headings substituting store. Logically they seem to be subheadings - at least in the list they are subheadings of the tab "store". This also saves horizontal space. Hitting the subheading could 
A) filter the list
B) jump to that section (might be the better solution)

Dropdown could be a way to go (Google chose this approach for the Play Store and its working for me), too. I just felt like I would need a way to view categories from first starting HACS.

Thanks for your hard work!

PS: Adding active tab indicators might also be an option.

**Comment by ludeeus** [comment]
![image](https://user-images.githubusercontent.com/15093472/65815668-f4636280-e1f2-11e9-9f65-123d2b2aed40.png)
WIP

**Comment by ludeeus** [comment]
For the installed/overview tab, are anyone going to be sad if I don't group them?
![image](https://user-images.githubusercontent.com/15093472/65838023-bce1dc80-e2fe-11e9-88f7-83fe8a8047b6.png)
