### ISSUE TITLE
Feature request: Create a bundle of all javascript cards

### ISSUE THREAD

**Issue by olekenneth** [custom-components/hacs#201]
I was thinking when updating Lovelace cards; if you where to build a bundle of all the files, then you wouldn't need to add every cards javascript files to the lovelace-config. 

I assume it might create a caching problem if hosted by home assistant, so you also might want to create a webserver for the hosting with strict cache-control headers.

**Comment by ludeeus** [comment]
This would indeed be a good feature, but I don't see this as being viable now.

- Some plugins require to be loaded before others.
- HACS cannot be 100% about the type to set.

Because of this, I can not provide a stable solution for this.
