### ISSUE TITLE
Cannot add hass-variables repo

### ISSUE THREAD

**Issue by commandcontrolit** [custom-components/hacs#203]
## Version of HACS
10

## Describe the bug
Trying to add https://github.com/rogro82/hass-variables as custom repo

Receive the following error:
Could not add rogro82/hass-variables at this time, check the log for more details.

## Debug log
Receiving error when clicking log

```text

500 Internal Server Error
Server got itself in trouble

```

**Comment by ludeeus** [comment]
That repository is not compliant.

**Comment by commandcontrolit** [comment]
Ah ok - sorry. Wasn't aware it needed to be compliant to be added. 

Thanks for the quick response and your addon!
