### ISSUE TITLE
The background task never ends

### ISSUE THREAD

**Issue by SomeoneCares** [custom-components/hacs#207]
## Version of HACS

HACS 0.10.0

## Describe the bug
the background task never ends and keeps running

## Debug log
this is what i have on the HA log

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase.py", line 70, in startup_tasks
    old_hacs = old.get("repositories", {}).get(repository.repository_id, {})
AttributeError: 'bool' object has no attribute 'get'

**Comment by lbouriez** [comment]
Hello, same on my side

**Comment by qman28** [comment]
I had the same problem.  I noticed after downloading v.0.10.0 it showed version DEV in hassio.  I had HACS update itself and restarted my VM and everything resolved.

**Comment by ludeeus** [comment]
Duplicate of #204
