### ISSUE TITLE
Ability to "Re-Install all"

### ISSUE THREAD

**Issue by SeLLeRoNe** [custom-components/hacs#210]
**Is your feature request related to a problem? Please describe.**
I have by mistake removed the "www" folder, this caused all the cards not to be working and I have to go on each of them and "Re-Install" in order to re-download the related files.

**Describe the solution you'd like**
A single button in the "Settings" Page to Re-Install (or re-download) all the "enabled" cards/plugins/components at once

**Describe alternatives you've considered**
Keeping doing it manually... but it's a pain! :D

**Additional context**

**Comment by ludeeus** [comment]
Will not be adding that.

What you can do is open your `.storage/hacs` file (take a backup of it first)
Then for all items, you have installed change `version_installed` and `installed_commit` to `"999"`

example:
from;
```
"installed_commit": "hfsd873",
"version_installed": "1.0.1",
```
to
```
"installed_commit": "999",
"version_installed": "999",
```
When you are done with all elements save the file, then restart HA.
When it has started and the initial background task is done you can use the "upgrade all" button under setting.

**Comment by SeLLeRoNe** [comment]
Okay thanks.
How about something that reset those values automatically?
Also, linked to this, I presume that because of HACS storing data in .storage.hacs that would need to be part of a backup and included in a brand new installation to keep track of the cards, am I correct?

Thanks

**Comment by ludeeus** [comment]
> How about something that reset those values automatically?

Use Regex search & replace.

**anything** you want to save, you should backup no matter what system it is.

**Comment by SeLLeRoNe** [comment]
For whoever might be interested on change all at once, here the commands:
sed -i 's/installed_commit": ".*/installed_commit": "0.0.0",/g' .storage/hacs
sed -i 's/version_installed": ".*/version_installed": "0.0.0",/g' .storage/hacs

Usually, so far, I was just saving my "customizations" as per entities, automations, etc.

I don't really think saving the .storage folder is needed to recover an installation, the hacs file would be to be able to not to have to "re-select" each custom thing that was installed :)

**Comment by ludeeus** [comment]
.storage contains information about your users, authentication, and onboarding status.
That + hacs files are definitely things you want to save.

**Comment by SeLLeRoNe** [comment]
Agree to disagree :)
I do see a reason for the hacs, re-creating a user on startup is not big deal on a restore and beside that, I am not storing anything from the UI.
To be honest, I am not sure what "onboarding status" means, but I guess I "skip" that bit using a MySQL Database :)

But beside that, thanks for your work and your help on this matter.
I will probably open a bug soon related to custom repos.
