### ISSUE TITLE
Add a tickbox in settings to always show beta updates

### ISSUE THREAD

**Issue by jameshiscott** [custom-components/hacs#211]
**Describe the solution you'd like**
I like to see that a beta install is available, so i enable "install beta" option on all of my installed custom cards. I then look at HACS it tells me something new i see if i want that beta update or not. 

Now with the select a version drop down, it would be nice to have a way to always show beta update (tickbox on the settings page) and then via the drop down, i could select if i want to stick with the current one or upgrade to the beta.

PS. Thanks for all your work on this, its amazing how quickly it is growing.

**Comment by ludeeus** [comment]
IMO pre-releases should not be used without the developer asking you to test those.
So this should stay the way it is with a pr. repository setting.

If you choose to change this for all repositories I can not stop you, but I will not make that easy.
There is also a limited number of repositories that actually use pre-releases.
