### ISSUE TITLE
HA unresponsive for a long time after "Reload data" button pressed

### ISSUE THREAD

**Issue by stepanov1975** [custom-components/hacs#22]
After "Reload data" button pressed HA goes unresponsive for a minute or two. This should not happen. I hope automations still able to run at this time, otherwise it is catastrophic. Such things should run in the background.

**Comment by ludeeus** [comment]
0.3.0 will fix that, and yes anything is qued up

**Comment by ludeeus** [comment]
This has been resolved in https://github.com/custom-components/hacs/releases/tag/0.4.0
