### ISSUE TITLE
Assets not coming from home card

### ISSUE THREAD

**Issue by soberstadt** [custom-components/hacs#220]
**Is your feature request related to a problem? Please describe.**
There is a lovelace card that I tried installing from HACS but it only brings the JS and not the image assets: https://github.com/postlund/home-card

![image](https://user-images.githubusercontent.com/1080613/60560542-3547fa00-9d1e-11e9-90b1-75370aeb1bd5.png)
![image](https://user-images.githubusercontent.com/1080613/60560552-3da03500-9d1e-11e9-833b-59cf2ede2c7d.png)

**Describe the solution you'd like**
Perhaps we have predefined folder(s) that HACS will also copy over into the `www` directory.

**Describe alternatives you've considered**
Perhaps I need to convince the plugin author to use releases.

**Additional context**

**Comment by ludeeus** [comment]
It needs to use a 'dist' dir as described in the plugin developer page.
