### ISSUE TITLE
custom-components/sensor.owlintuition

### ISSUE THREAD

**Issue by tomlut** [custom-components/hacs#221]
## Describe why you are flagging this
I am getting errors for it and it is not installed.

`custom-components/sensor.owlintuition - Server Error`

**Comment by ludeeus** [comment]
If you have issues with installation open an issue where you fill out the issue template, I personally tested this and it works.

**Comment by tomlut** [comment]
I have not installed it. I do not want to install it. Hacs is the only place owl intuition exists in my HA set up yet I see the error I posted. Why?
