### ISSUE TITLE
Requirements on Installation page not acurate

### ISSUE THREAD

**Issue by voodoobg** [custom-components/hacs#223]
## Describe why you are flagging this
Tried to install it on Hassio v. 0.92.1 (moved my installation from RPI to NUC with this version), put the files in the custom_components, but when i put hacs: and the token the validator said hacs component not found. Checked everything a couple of times with no luck. After all I decided to update to the final version and it works as it should. So for me it's not working on version 0.92.1

**Comment by ludeeus** [comment]
You get that issue if you do not restart HA after adding it to your filesystem before adding the configuration.
