### ISSUE TITLE
More options to STORE

### ISSUE THREAD

**Issue by jojoro1** [custom-components/hacs#229]
Can You add some features to store?

1. How often integrations/plugins were downloaded
2. Ratings by users
3. Sorting by last modification/rating/nuber of downloads
4. Screenshots maybe?

**Comment by ludeeus** [comment]
This will not be possible without a centralized server that every instance push data to, I would not use an integration that did that.

The developer can add screenshots the the `info.md` file.
https://custom-components.github.io/hacs/developer/general/#enhance-the-experience
