### ISSUE TITLE
Component not found: hacs

### ISSUE THREAD

**Issue by Max1963** [custom-components/hacs#233]
Version of HACS: 0.11.1
Version of Home Assistant: 0.93.1

## Describe the bug: Configuration not valid.
                                  Component not found: hacs

After copy downloaded hacs dir into custom_components dir and add:

hacs:
   token: MYGitHubToken

to my configuration.yaml

HA don't show HACS tab and configuration check gives that error.

**Comment by ludeeus** [comment]
Then you are missing step 7
<https://custom-components.github.io/hacs/installation/manual/#step-7-restart-home-assistant>

**Comment by Max1963** [comment]
I've restarted Ha but nothing changed. Have also delete all and restart
installation of Hacs but get same error.

Il dom 7 lug 2019, 13:04 Joakim Sørensen <notifications@github.com> ha
scritto:

**Comment by ludeeus** [comment]
Set logging to debug and add the _entire_ log here by using hastebin.

**Comment by Max1963** [comment]
After an hard reset (toggle Raspberry PI power) now works fine. Don't know why don't working when restart from HA.
