### ISSUE TITLE
Releases not found for custom repository

### ISSUE THREAD

**Issue by MatthewFlamm** [custom-components/hacs#238]
## Version of HACS
0.11.1

## Describe the bug
I have a custom repo with tags but only the last commit shows up.

https://github.com/MatthewFlamm/nwsradar/

![Screenshot_20190707-200055](https://user-images.githubusercontent.com/39341281/60775507-f6d18700-a0f1-11e9-9d80-0a5194b811d5.png)

![Screenshot_20190707-195858](https://user-images.githubusercontent.com/39341281/60775488-c25dcb00-a0f1-11e9-93d9-3c2ac858ed11.png)

## Debug log

No errors in log.

**Comment by ludeeus** [comment]
Those are not releases, but tags.
For now, it can only look for releases.

**Comment by MatthewFlamm** [comment]
You are correct.  It is baffling that GitHub shows them as a release when they are not.  Thanks!
