### ISSUE TITLE
Mark A seen button

### ISSUE THREAD

**Issue by vandalon** [custom-components/hacs#239]
Hi, you awesome dude who made my life a bit easier :)

I think it would be nice to have a mark as seen button next to each item so I don't have to open the link to the plugin/integration to mark it as seen :)

Just my 2 cent.

Thanks for the great work!

**Comment by ludeeus** [comment]
This will add unnecessary clutter to the view for an operation you will execute once.

**Comment by pareidolialjebus** [comment]
This should be reopened as a single button to "mark all as seen" from the config screen.  as a new user this is like being forced to play "whack a mole" for hours.  OK, you only have to do it once, but it takes ages and feels unnecessary.  Either that, or make the first install put everything in as read, so only the new stuff shows up.  Other than this, I have to say the experience is flawless.
