### ISSUE TITLE
The description of the component is not updated if it change in Github

### ISSUE THREAD

**Issue by hakana** [custom-components/hacs#24]
## Version of HACS
0.1.0

## Describe the bug
When the description of the repro is updated it still the old one in HACS.

**Comment by ludeeus** [comment]
You should be using v0.2.1, but I don't think that will help.
I have tested this on my dev system (running the upcoming version) an there it updates.

**Comment by ludeeus** [comment]
This was fixed... But I checked now, that bug is back, will look into it to the next version.

**Comment by ludeeus** [comment]
0.4.2 includes a fix for this.
