### ISSUE TITLE
Problem with CSS Styles after upgrade

### ISSUE THREAD

**Issue by matisaul** [custom-components/hacs#241]
## Version of HACS

0.11.0

## Describe the bug
Problem with HACS CSS Styles. After upgrate to 0.11.1, I have this view:
https://imgur.com/NzxVWIG

Please look at the Chrome Console errors.

## Debug log

```text

Failed to load resource: the server responded with a status of 404 (Not Found)
materialize.min.css.gz:1 
Failed to load resource: the server responded with a status of 404 (Not Found)
all.min.css.gz:1 
Failed to load resource: the server responded with a status of 404 (Not Found)
hacs.js:45 Uncaught ReferenceError: M is not defined
    at HTMLDocument.<anonymous> (hacs.js:45)
hacs.js:51 Uncaught ReferenceError: M is not defined
    at HTMLDocument.<anonymous> (hacs.js:51)
4
fetchWrapper.mjs:111 
Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at Object.fetch (fetchWrapper.mjs:111)
    at async o.u (StaleWhileRevalidate.mjs:182)
materialize.min.css.gz:1 Failed to load resource: the server responded with a status of 404 (Not Found)
all.min.css.gz:1 
Failed to load resource: the server responded with a status of 404 (Not Found)

```

**Comment by ludeeus** [comment]
Restart HA.

From what version?

**Comment by matisaul** [comment]
> Restart HA.
> 
> From what version?

I restarted HA several times but It always the same. I have Hassio 0.95.4

**Comment by ludeeus** [comment]
What version of _HACS_ did you use before the upgrade?
You are missing a lot of files and need to reinstall HACS.

**Comment by matisaul** [comment]
I had the 0.6.0 version... Is there a safe way to reinstall without loose my installed plugins?

**Comment by ludeeus** [comment]
That version did not have the logic to download the extra style files.

All "upgrades" are reinstallations, so the info about what you have installed are untouched (they are safe under . storage)

**Comment by matisaul** [comment]
So.. If I remove the hacs folder fom custom_component, and copy the new version, It will be just fine, right?

**Comment by ludeeus** [comment]
That is correct, nothing of importance is stored there

**Comment by matisaul** [comment]
Thanks!! Now It's working again
