### ISSUE TITLE
Hide items I flag as not applicable

### ISSUE THREAD

**Issue by screzwell** [custom-components/hacs#243]
Could we have a way of flagging integrations and plug ins that will never be applicable to us i.e. Plug ins related to other countries or devices I will never own.  Maybe move them to another tab so they're still accessible in the future, but not on the store screen.
I feel as more custom items get added this will  be a way to tidy up the long list.

**Comment by ludeeus** [comment]
Just hide them from the menu inside each element.
![image](https://user-images.githubusercontent.com/15093472/60840850-ae3ccb00-a1d0-11e9-9a35-5d86ead3ee9d.png)
