### ISSUE TITLE
Status Colours

### ISSUE THREAD

**Issue by mynameisdaniel32** [custom-components/hacs#246]
**Is your feature request related to a problem? Please describe.**
When using HACS, it's hard to see the current status of packages as the colours used are very subtle/dark. I'm not colourblind, but if someone was they'd have a particularly hard time.

**Describe the solution you'd like**
The colours are very useful, they should all be more prominent. The yellow for example (when an update is available), stands out.

**Describe alternatives you've considered**
Different icons to represent the states would also be worthwhile.

**Additional context**
For example, two of these are red, two are green.
![image](https://user-images.githubusercontent.com/24840952/60850467-a744a580-a22e-11e9-8646-fabdd7d1da37.png)

**Comment by ludeeus** [comment]
Those can be changed in your theme <https://custom-components.github.io/hacs/usage/theming/>
