### ISSUE TITLE
One spot for all plugin resource links

### ISSUE THREAD

**Issue by Sandersjr1** [custom-components/hacs#249]
A way to see all the plugin resource links in one spot instead of opening each plugin to copy the resource link.

Example lovelace.yaml:
resources: !include /community_plugin/resources.yaml
 ```
  - url: /community_plugin/bar-card/bar-card.js
    type: js
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/button-entity-row/button-entity-row.js
    type: js
```

Since the the code is already finding the url and type and putting it in a box. 

Adding the box to a file or location would be easy.
Removing the plugin resource may be the challenging part.

This could allow for easier adding.

another issue will be making sure type is set correctly

**Comment by ludeeus** [comment]
I will not add this because of these reasons:

- I can not guarantee that all types will be correct, some repos are missing that.
- This information you need 1 time.
