### ISSUE TITLE
Possibility to add custom repro's in the standard store 

### ISSUE THREAD

**Issue by hakana** [custom-components/hacs#25]
Possibility to add custom components in the default store. 

**Describe the solution you'd like**
Possibility to add custom components in the default store. In that way it will be easier to find different components just by search the store. Maybe also add categories for components so the user easy can find different components.

**Comment by ludeeus** [comment]
So this is kinda two parts, let's get the easy one out of the way, in the next version you can search for "categories" (repository topics), so here can the developer go wild when adding topics to their repo.

For the main part of this issue.
**A global catalog (CG).**
For this to be a viable option I think this should cover most issues,
- New "entries" in the GC are added by the form of a PR against a var in the [`const.py`](https://github.com/custom-components/hacs/blob/prefupdate/custom_components/hacs/const.py#L32) file.
- One PR pr entry.
- Entries are **only** accepted if they are added by the owner (or a major contributor) for that repo.
- The repo must follow all requirements (must be possible to add it manually)
- When accepted (merged) that repo will be a part of the next minor update.

Before I take the step to enable this, I must first do this:
- Give the user an option to hide repos the user do not want to see (hidden repos, will be shown under the settings tab, with the option to unhide).
- There will have to be some kind of report system (button that takes the user to a defined issue template)

But the most important thing, I want feedback from both users and developers on this before I do anything.
So use your "voice" and add your comments here :)

**Comment by iantrich** [comment]
OR, convince devs to move to the custom orgs :)

**Comment by maykar** [comment]
Being able to add repos to the default collection would be appreciated :)

**Comment by hakana** [comment]
Sounds like a perfect solution!

**Comment by DavidFW1960** [comment]
I'm not sure I understand the point of this TBH... to make it easier for users to find a custom component? Or to find custom cards? I'm generally going to find those by reading the forums and lets face it, there are devs who just aren't even willing to follow the structure necessary to have their work in HACS at all  - even ones who support custom_updater.

I'm sure a custom global catalog would be a good idea for the users though.

I don't know if users need to be able to hide repos... I think the search function cuts that clutter down.

Or am I just misunderstanding this?

**Comment by ludeeus** [comment]
No, you are not :)

This will mean that if a developer added a repository to be included by default, new awesome stuff would just "pop" up in the store when you upgrade HACS to a version that has that included.

For the hidden part of this, this is useful for two reasons:
- let's say a component that tracks apple devices are added, you do not own an Apple device, so you will never use/install that, hiding it make sure that you do not see it (yes search can help with this too.)
- The other reason, let's say 100 repositories are added, the way HACS works is that everything is processed locally, repositories that are hidden will not be processed, this will help with performance.

**Comment by ludeeus** [comment]
With that said, the option to hide will be there in the next version no matter how this FR turns out since that can help with performance.

**Comment by ludeeus** [comment]
So what this boils down to now:

## To the user

Would you be okay if when you upgrade HACS, there is a possibility that new awesome stuff is automagically added to the "store"?

**Comment by DavidFW1960** [comment]
That will certainly help us discover awesome new stuff....

**Comment by ludeeus** [comment]
Then it's settled.
If anyone has an objection to this, please say something.
If not this will be a possibility from 0.6.0 that I plan to release tomorrow or Monday :)

**Comment by ludeeus** [comment]
https://custom-components.github.io/hacs/#include-default-repositories

**Comment by ludeeus** [comment]
Starting <https://github.com/custom-components/hacs/releases/tag/0.6.0> this is now included.
