### ISSUE TITLE
Keeping config in git

### ISSUE THREAD

**Issue by brondum** [custom-components/hacs#254]
## Version of HACS
0.11.1

## Describe the bug
I am not sure it is a bug as such. I am keeping all my config in git (makes sense right). Except secrets of cause.

Each commit then triggers my CI/CD pipeline, which first tests the config and if this succeeds it will deploy the commit, simple and easy.

BUT, when i add a custom_component through hacs, this is of course not added to my git repo as this is installed directly in my HASS installation. 

I have tried copying the folder to my git repo but when i run the test i still get:
`$ hass --script check_config -c ./data/
INFO:homeassistant.util.package:Attempting install of aiofiles==0.4.0
Failed config
  General Errors: 
    - Platform not found: sensor.unifigateway`

Any ideas on how to get around this, cause i really like the idea of have the Community Store looking for updates etc.

**Comment by ludeeus** [comment]
> I am not sure it is a bug as such.

Correct, this is not a bug with this integration, but a generall issue with your flow.

>Any ideas on how to get around this.

Have your CI install all `requirements` from the manifest files for the various components before checking.

**Comment by brondum** [comment]
@ludeeus Can you give me a pointer on how i can load these before running:  `hass --script check_config -c /config`

It seems like the check_config dont load them automatically ? 

Thanks in advance

**Comment by ludeeus** [comment]
Check _any_ of the load configs here <https://github.com/custom-components/hacs/tree/master/.pipelines>
