### ISSUE TITLE
Add padding to buttons on mobile screen

### ISSUE THREAD

**Issue by JuanMTech** [custom-components/hacs#255]
![Screenshot_20190710-161911_Chrome](https://user-images.githubusercontent.com/23154499/61001996-ae52dd00-a32e-11e9-9d90-bdb403e6a838.jpg)

Add padding to buttons on mobile screen.

**Comment by ludeeus** [comment]
Corrected in https://github.com/custom-components/hacs/releases/tag/0.12.0
