### ISSUE TITLE
Custom Integration listing

### ISSUE THREAD

**Issue by pilotak** [custom-components/hacs#257]
I have several custom_components that i would like to be listed in store so i followed the instructions, splitted them into separate repos and they are still not showing up. Or do i have to get them listed in `data` branch?

https://github.com/pilotak/homeassistant-clientraw
https://github.com/pilotak/homeassistant-attributes
https://github.com/pilotak/homeassistant-mikrotik

**Comment by ludeeus** [comment]
<https://custom-components.github.io/hacs/developer/include_default_repositories/>
