### ISSUE TITLE
New feature update notify and a button to set all element in store no "New"

### ISSUE THREAD

**Issue by michelebossa** [custom-components/hacs#263]
Hi,
Great Job the tools it is amazing i'd like if it is possible two new feature:
1)  For the new element into tab store there is a label "New" can you add a button to set all element not New (Because at moment i have all with these label and i can't understand the new element showed in the list )
2) The HACS can send a notify when there is a new update to do? 

Thanks

**Comment by ludeeus** [comment]
1 No
2 Create an automation based of the sensor from it.
There are an example here <https://community.home-assistant.io/t/custom-component-hacs/121727/157?u=ludeeus>

**Comment by michelebossa** [comment]
Thanks
