### ISSUE TITLE
[Question] what is HACS doing at boot time, it seems to load a lot of stuff i'm not interested in....

### ISSUE THREAD

**Issue by alain57** [custom-components/hacs#265]
each time I start HA i see in my logs TONS of stuff like this
[custom_components.hacs.storage] Loading blablabla 
and of couse the line is a component i never installed.

This all happens on mainThread and is taking a long time
it is not clear what it does, does it ask all githubs project if new version of these components are present ? 
If yes wouldn't it make more sense to have one uniq webservice that return the version of all plugins at once.
The webservice could check all githubs registered services (at least the one available in hacs repository) for a new version once per day or once every 6hours
That way it would not do lots of strange background work.

If not possible, maybe do this on another thread or even better on multi thread, that way it would not look like a sequential query

**Comment by ludeeus** [comment]
It loads stored information during startup and updates information about the things you have installed.
If you do not want to see those logs, change your logger settings.

This happens in the MainThread yes, but does not interfere with the rest of the system.

And external Webservice will not happen.
