### ISSUE TITLE
GitHub stars

### ISSUE THREAD

**Issue by towerhand** [custom-components/hacs#267]
**Is your feature request related to a problem? Please describe.**

The list of available plugins and Lovelace cards is quickly growing.

**Describe the solution you'd like**

Main goal => Adding the GitHub star count next to name on the list would help highlight the most popular ones.

Also, hopefully will encourage people to visit the GitHub page of their favorite add-ons and star them too.

**Comment by iantrich** [comment]
It's pretty unlikely that people will go from hacs to Star a repo IMO

**Comment by ludeeus** [comment]
If you want this to be added to the overview/store pages, then no, I do not want to add "clutter" to those.

But inside the individual pages, maybe.

@iantrich It can be done with an API call ;)

**Comment by towerhand** [comment]
I agree but I do think power users usually star the repos more often than regular users so showing the number of stars would still help highlight the popular ones, especially as the list of available cards and plugins keep growing.

**Comment by ludeeus** [comment]
Create a mockup of how it should be shown, and I'll add a poll on the forum page.

**Comment by ludeeus** [comment]
There are 2 major drawbacks to adding this:

- It adds 2 API calls extra for _each_ element every 8h.
- The data will not be correct since it's only updated every 8h.

**Comment by Gary-B2** [comment]
Can you add it as a toggle feature so can be turned on or off as people prefer?

**Comment by ludeeus** [comment]
I tried to add this, the data was wrong, especially if you restart often.
Developers that want to show this, can add it to their info.md file.
