### ISSUE TITLE
sidepanel_title is an invalid options

### ISSUE THREAD

**Issue by geinzmrk** [custom-components/hacs#269]
HACS 0.11.1

## Describe the Problem

I added this to my configuration.yaml 

_hacs:
 token: 5fXXXXXXXXXXXXXXXXXX60
 sidepanel_title: test_

Error is:
Invalid config for [hacs]: [sidepanel_title] is an invalid option for [hacs]. Check: hacs->hacs->sidepanel_title. (See /config/configuration.yaml, line 64). Please check the docs at https://home-assistant.io/components/hacs/

Add your logs here.

```

**Comment by ludeeus** [comment]
It's not valid until 0.12.0
