### ISSUE TITLE
PSA: next version is delayed

### ISSUE THREAD

**Issue by ludeeus** [custom-components/hacs#27]
I had a plan to release the next version (`0.3.0`) yesterday.

There is so much I ~~need~~ want to get into this (without breaking existing installations).

**Some highlights:**

- Repositories that publish the plugin files as release assets are now supported
- Full rewrite of the update functions to save time/calls

Hopefully, I'm able to push this out later this weekend, if not it will be early next week.

[Most of the progress can be followed here](https://github.com/custom-components/hacs/compare/master...prefupdate) **(Don't try to run that branch, it's far from finished/stable)**

**Comment by iantrich** [comment]
We understand. 🍺comes first 😂

**Comment by maykar** [comment]
Slacker! :laughing:

**Comment by ludeeus** [comment]
The current code is partially broken, I'm aiming for a release sat/sun (ETC)

**Comment by ludeeus** [comment]
https://github.com/custom-components/hacs/releases/tag/0.4.0
