### ISSUE TITLE
Integration version check isn't working properly

### ISSUE THREAD

**Issue by smartHomeHub** [custom-components/hacs#271]
## Version of HACS
0.11.1

## Describe the bug
It seems that integration version check isn't working properly, at least for HA beta versions. HACS allows me to install my integration flagged as  "homeassistant": "0.96.0b1" in the manifest to an 0.96.0b0 HA instance.

## Debug log

```text

-

```

**Comment by ludeeus** [comment]
It is actually working as intended, it does not care about beta versions since breaking changes does not happen there.

It checks the 6 first characters of the installed version against the 6 first characters in the manifest.

**Comment by ludeeus** [comment]
That will break when HA goes beyond 0.100.x
Will move to LooseVersion from distutils.version in the next version

**Comment by ludeeus** [comment]
![image](https://user-images.githubusercontent.com/15093472/61181158-7abfcd80-a622-11e9-84ae-6d0ee8db2c7d.png)

**Comment by smartHomeHub** [comment]
> It is actually working as intended, it does not care about beta versions since breaking changes does not happen there.
> 
> It checks the 6 first characters of the installed version against the 6 first characters in the manifest.

We had a breaking change between b0 and b1 versions. I know, it is paranoid to care about beta breaking changes, but there are always people say "Hey, the component is not working with the latest beta. Please fix it."

**Comment by ludeeus** [comment]
yeah..

Will hopefully ship 0.12.0 which can handle that later today, or tomorrow (UTC)

**Comment by ludeeus** [comment]
Corrected in https://github.com/custom-components/hacs/releases/tag/0.12.0
