### ISSUE TITLE
Custom Repo for smartthinq is crashing Home Assistant

### ISSUE THREAD

**Issue by Nealtron** [custom-components/hacs#272]
HACS version: 0.11.1
Home Assistant version: 0.95.4

URL of repo: https://github.com/boralyl/hass-smartthinq

Home Assistant crashes if I attempt to open the smartthinq tile or use the upgrade all button from the HACS settings menu.

**Comment by ludeeus** [comment]
That repo is not compliant to use with HACS, if it gives you issues, remove it.

**Comment by Nealtron** [comment]
There in lies the problem, any attempt to view either the component or repo causes home assistant to crash. I'd happily remove it, but I don't see how I can. 

I now understand that it's not a compliant repo, but I would expect some amount of error handling to prevent a full blow crash.

**Comment by ludeeus** [comment]
Restart HA and it should be gone.
