### ISSUE TITLE
KeyError: 'schema'

### ISSUE THREAD

**Issue by P2mb2** [custom-components/hacs#274]
When I restart HA, after HACS installation i got the following error:

```
2019-07-14 10:48:59 INFO (MainThread) [custom_components.hacs] Runing startup tasks.
2019-07-14 10:48:59 INFO (MainThread) [custom_components.hacs] Trying to load existing data.
2019-07-14 10:48:59 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase.py", line 62, in startup_tasks
    await self.migration.validate()
  File "/config/custom_components/hacs/hacsmigration.py", line 30, in validate
    elif self._old["hacs"]["schema"] == "1":
KeyError: 'schema'
```

I already activated 
  logs:
    custom_components.hacs: debug

but no more information :(

**Comment by ludeeus** [comment]
Are there anything in `.storage/hacs` ?
Which version of HACS are you running?

**Comment by P2mb2** [comment]
Running the last version. Installed just this morning...

Yes i have a file on .storage/hacs.
SHould i remove it ?

**Comment by ludeeus** [comment]
"Latest" is not a version...

Don't remove it, use hastebin and paste the content here.

**Comment by P2mb2** [comment]
ludeeus, 

I had a different installation in the past... for some time i didn't use it. When i tryed to load last week i got the "Background task running, refresh the page in a little while.". I rebooted but nothing happened... so... i decided to remove costum_components/hacs folder and all the cached files under /costum_components

I copied the folder from version 0.11.1 and reboot again. I thought everything from HACS will be under /costum_components/hacs folder. 

Please check here the .storage/hacs: 
https://pastebin.com/ht7sw4L4

**Comment by ludeeus** [comment]
that is a file for a really old version :)

Since you have not installed anything, remove that file, then restart HA.

**Comment by P2mb2** [comment]
removed. Error gone.
THanks for the quick and accurate support ludeeus.
Cheers.
