### ISSUE TITLE
After updating to 0.12.0 everything says "Could not determine the type of this plugin"

### ISSUE THREAD

**Issue by SeanPM5** [custom-components/hacs#277]
## Version of HACS
0.12.0

## Describe the bug
After updating to v 0.12.0, at the very bottom of the page where it says "When you add this to your configuration use this" and it has the copy to clipboard thing with the resources... I get this on every single thing that I've looked at so far, even things I've already installed and know were correct before:

`Could not determine the type of this plugin, check the repository.`

**Comment by ludeeus** [comment]
Fixed in 0.12.1 https://github.com/custom-components/hacs/releases/tag/0.12.1
