### ISSUE TITLE
Display tooltip on hover for status icons

### ISSUE THREAD

**Issue by SeanPM5** [custom-components/hacs#282]
**Is your feature request related to a problem? Please describe.**
HACS shows helpful status icons (green, orange, red) but this could potentially be a little confusing for users if they haven't read the docs. For example, the red "restart pending" icon color could be misinterpreted as an error/failure. 

**Describe the solution you'd like**
Could solve this by displaying a standard browser tooltip when hovering over the status icons with a mouse. Here is a rough mockup:

![tooltip](https://i.imgur.com/g8GBlm4.png)

Potential wordings to use:
Green: "Up to date!"
Orange: "Update available."  (or... "Button Card 1.11.1 available. You're using 1.10.2.")
Red: "Restart to finish installing or updating."

**Comment by ludeeus** [comment]
Adding it to the icon can not be done, since the entire line is an active object.

But it can be added to the line (in table) or card (in grid).

**Comment by ludeeus** [comment]
NVM.. looks like that is no longer a limitation with the new generation logic.
Added for 0.13.0

**Comment by ludeeus** [comment]
<https://github.com/custom-components/hacs/blob/40cacd0445f668ebd1df7575934f0bf81898fb5d/custom_components/hacs/repositories/repositoryinformation.py#L87-L95> Current descriptions.
