### ISSUE TITLE
Page not found after update hacs

### ISSUE THREAD

**Issue by filmgarage** [custom-components/hacs#283]
## Version of HACS

from version 0.11 to 0.12.1

## Describe the bug
After updating has I receive this error:

No such file or directory: '/config/custom_components/hacs/frontend/elements/repository/pending_restart.html'

It seems like the update wants to show a page asking for a restart, but the page is not available on my system...

**Comment by ludeeus** [comment]
_Please read release notes **before** upgrading._

This is described there ;)
<https://github.com/custom-components/hacs/releases/tag/0.12.0>

**Comment by filmgarage** [comment]
Excellent! I should have read better! :-)
