### ISSUE TITLE
HACS reinstall button is alwasy showing up

### ISSUE THREAD

**Issue by BartEngelen** [custom-components/hacs#286]
## Version of HACS

0.12.1

## Describe the bug

HACS stays on reinstall.
I have click it several times and rebooted Home Assistant also several times.
I see a green icon in the overview when I click then I see reinstall.
What can be the problem ?

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
that is not a problem, that is the expected behavior.
