### ISSUE TITLE
TypeError: buttons[button].shadowRoot is null

### ISSUE THREAD

**Issue by tomlut** [custom-components/hacs#287]
## Version of HACS

0.12.1

## Describe the bug
The following error is appearing in the log:
```
https://10.1.1.100:8123/community_plugin/compact-custom-header/compact-custom-header.js:446:1 TypeError: buttons[button].shadowRoot is null
```
I do no have the button card installed. I did but that was a while ago.

## Debug log

```text

As per the bug description.

```

**Comment by ludeeus** [comment]
This is not an issue with HACS, but with CCH.

**Comment by tomlut** [comment]
Ugh. Sorry. Doing too many things at once.
