### ISSUE TITLE
The overview page does not work - It shows an error message

### ISSUE THREAD

**Issue by jdestefanis** [custom-components/hacs#288]
## Version of HACS
Last one

## Describe the bug
When I click on the Overview button the page is not being shown. It says Something is wrong...
Error code: Kneel before Zod!

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
Enable debug logging, then restart and paste the logs _after_ you try it again.

**Comment by quantummobile** [comment]
`[Errno 2] No such file or directory: '/config/custom_components/hacs/frontend/elements/repository/row_overview.html'
7:05 PM custom_components/hacs/frontend/views/overview.py (ERROR) - message first occured at 7:01 PM and shows up 16 times
`

**Comment by ludeeus** [comment]
Restart Home Assistant, as stated in the release notes.
