### ISSUE TITLE
Removing old custom_updater breaks lovelace

### ISSUE THREAD

**Issue by DavidFW1960** [custom-components/hacs#29]
Newest version installed today
## Describe the bug
I removed the old custom_updater from configuration.yaml and added HACS as per the instructions.

In HACS I added the tracker card... I thought this would mean that my lovelace cards using the /customcards/ endpoint would still work? I am now seeing red screens for all cards not used by HACS.

Should I change the endpoint back to /local/ or should I use the new /community/ endpoint now?

## Debug log

```text

No real log to add. Just getting custom element does not exist errors.

Add your logs here.

```

**Comment by r3mcos3** [comment]
`Moving from custom_updater
If you have custom_updater installed you need to remove that (rename the directory or delete it completely). You will also need to remove the custom_updater entry from your configuration.yaml file.

This and custom_updater can not operate on the same installation.

If you used the special endpoint /customcards/ endpoint for your Lovelace cards, you now need to reinstall that plugin using HACS and use the url provided in the page for that plugin in the HACS UI, if the plugin is not there you need to use /local/ insted.

As noted under ‘Existing elements’ You need to click the “INSTALL” button for each element you previously have installed.

**tracker-card will not work with hacs **

`

**Comment by DavidFW1960** [comment]
So why is it in the HACS store?

**Comment by r3mcos3** [comment]
I don't know but tracker card only works with custom updater

**Comment by ludeeus** [comment]
It's there because currently, that is a valid repo.
Will be removed in the next version <https://github.com/custom-components/hacs/commit/572bd578052523422f1b5a9035e5de72e38ad865>

**Comment by DavidFW1960** [comment]
It also sucks that customcards endpoint gets around the caching problem of the local endpoint and now here we are regressing functionality.

**Comment by ludeeus** [comment]
`/community_plugin/*` that are used for plugins managed by this have the same anti-cache properties ;)

**Comment by DavidFW1960** [comment]
Yes but what about cards like the custom-button-card or @iantrich template card that are not supported by HACS but work with /customcards/ and custom updater?

**Comment by ludeeus** [comment]
It works the same way, and that particular card should be there, and will be soon.

**Comment by DavidFW1960** [comment]
So instead of using /local/ I can use the new endpoint even for cards not supported by HACS?

**Comment by DavidFW1960** [comment]
So currently I have 2 custom components not supported by HACS - Authenticated (One of yours) It gives an error when I try and add https://github.com/custom-components/sensor.authenticated, then lists it anyway, but the component isn't in the list of ones I can then manage. The other custom component is Phil Bruckner's sun.py replacement of the inbuilt component and as far as I know he does not plan to support HACS.

Custom Lovelace cards not supported:
Mark Frankland's darksky
Kalkih's mini-media-player and mini-graph-card
Button-card (You say coming soon)
and also @iantrich config-template-card (coming?) and podcast-card.

I don't think I can use these without reverting to the /local/ - does not work with other endpoints.

There also seems to be no kind of in-your-face notifier that an update is available like there is for the old tracker card.
