### ISSUE TITLE
"New" icon position

### ISSUE THREAD

**Issue by 3ative** [custom-components/hacs#292]
**Is your feature request related to a problem? Please describe.**
"New" Icon was easier to see/find when it was on the right-hand side

**Describe the solution you'd like**
Would it be possible to put the "New" Icon back on the right?

**Describe alternatives you've considered**
Have the "New" icon flash?

**Additional context**

**Comment by ludeeus** [comment]
The issue with having it there was that it was so "annoying" for users that I got a request daily to add a button to remove all of them, I believe this is a good compromise.

**Comment by 3ative** [comment]
@ludeeus I see... shame, it was so much easier to see what's 'New' when it was on the right. 
Ok, thanks for the reply.

**Comment by ludeeus** [comment]
You can do a search for "NEW" in the store, then you will only see new items :)

**Comment by 3ative** [comment]
@ludeeus Oh really?? Cool, I'll give that a go. Cheers
