### ISSUE TITLE
Error rendering info template 'states' is undefined

### ISSUE THREAD

**Issue by TorqueDelight** [custom-components/hacs#294]
## Version of HACS
0.12.1

## Describe the bug
A few times a day, I get this error in the logs

Everything seems to be working fine but I wanted to point that out...

## Debug log

```text

WARNING (MainThread) [custom_components.hacs.template] Error rendering info template 'states' is undefined

```

**Comment by ludeeus** [comment]
That is a warning, not an error.
I'll hide it in the next version.

**Comment by Pirol62** [comment]
There is a new one with the same characteristic:

Error rendering info template 'value' is undefined
one minute befor the standad states warnung appears
