### ISSUE TITLE
To correct Secondaryinfo Entity Row install

### ISSUE THREAD

**Issue by hellcry37** [custom-components/hacs#303]
## Version of HACS

0.12.1

## Describe the bug
to edit Secondaryinfo Entity Row
from:
- url: /community_plugin/secondaryinfo-entity-row/secondaryinfo-entity-row.js
  type: js
to:
- url: /community_plugin/secondaryinfo-entity-row/secondaryinfo-entity-row.js
  type: module

Without this doesn't work!
Also please add "thomasloven/lovelace-card-tools" without them Secondaryinfo Entity Row doesn't work.
https://github.com/thomasloven/lovelace-card-tools

Thanks for your great work,
Ciprian
## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
The type is parsed from the README in the repo, it uses the first `type: ` it finds.
This is not something I can change.

Adding repos are up to the developer of that repo, and is not something I will do.
