### ISSUE TITLE
HACS and safepay/sensor.fronius broken HA

### ISSUE THREAD

**Issue by adtwomey** [custom-components/hacs#308]
## Describe the bug
HA 0.96 came up with  coming up is Unable to connect to Home Assistant.

## Debug log
https://gist.github.com/adtwomey/fb75112770287488b938c21d538802d8

Thanks for your Hard work

**Comment by ludeeus** [comment]
The issue here is that in the manifest for `safepay/sensor.fronius` the `domain` key changed it's value.

**Comment by ludeeus** [comment]
<https://community.home-assistant.io/t/fronius-inverter-integration/19274/134?u=ludeeus> workaround posted here.
