### ISSUE TITLE
I'm getting log errors from cards I don't have intalled

### ISSUE THREAD

**Issue by Pirol62** [custom-components/hacs#309]
## Version of HACS
O. 12.1

## Describe the bug

PiotrMachowski/Lovelace-Xiaomi-Vacuum-Map-card - No acceptable js files found# Debug log
and a second one:

safepay/sensor.fronius - custom_components/fronius does not exist in the repository.
12:18 custom_components/hacs/handler/logger.py (ERROR)!-- 

To enable debug logs check this https://www.home-assistant.io/components/logger/ -->

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
"PiotrMachowski/Lovelace-Xiaomi-Vacuum-Map-card" have now been removed.
"safepay/sensor.fronius" Changed it's name yesterday.

On the next check, this will be OK. (runs every 8h)

**Comment by Pirol62** [comment]
Sorry - hope you look into this.
I have one more:
![image](https://user-images.githubusercontent.com/48820003/61608928-d7d80680-ac54-11e9-9902-cb1b4b416ed0.png)
