### ISSUE TITLE
How to make HACS read and display info.md

### ISSUE THREAD

**Issue by DavidFW1960** [custom-components/hacs#317]
How do I get HACS to display my info.md when someone opens my plugin/integration? I have an info.md file but it is not displaying that when someone opens the card. Am I missing something to make it display?

**Comment by ludeeus** [comment]
When you use releases, HACS display infromation about the selected release (version)
https://github.com/DavidFW1960/bom_forecast/tree/0.1 Does not contain a info file.
Master does:
![image](https://user-images.githubusercontent.com/15093472/61588290-35a71880-ab99-11e9-8d5f-a5e7938f2632.png)
