### ISSUE TITLE
I'm getting more and more error entries during the day related to hacs

### ISSUE THREAD

**Issue by Pirol62** [custom-components/hacs#318]
## Version of HACS
0.12.1

## Describe the bug
![image](https://user-images.githubusercontent.com/48820003/61588703-63dc2680-aba0-11e9-8405-e2a7adcd7686.png)
This issue showed 5 times yesterday.
Starting at this point today
Has nothing to do with hue component. There could be any component or card
## Debug log

```text

Log Details (ERROR)
Sun Jul 21 2019 10:07:22 GMT+0200 (Mitteleuropäische Sommerzeit)
robmarkcole/Hue-sensors-HASS - Server Error

```

**Comment by ludeeus** [comment]
Server error, is when Github have issues.
What does it say in the logfile?

**Comment by Pirol62** [comment]
Nothing Else. Exactly what I have postet

**Comment by ludeeus** [comment]
That is **not** the log file...

**Comment by Pirol62** [comment]
Oh, pls point me into the right direction. Which log-file? I reduced logging to fatal errors

**Comment by ludeeus** [comment]
https://www.home-assistant.io/components/logger/

**Comment by Pirol62** [comment]
Ok, I know. As I wrote. Logger is reduced to Fatal Errors and due to that empty
