### ISSUE TITLE
Integration not found when trying to verify its sensor platform

### ISSUE THREAD

**Issue by circa1665** [custom-components/hacs#320]
I recently uninstalled the below from hacs:

- Plex Recently Added
- Upcoming Media Card

I'm now seeing the following error when I check my config:
```
Configuration invalid
Integration plex_recently_added not found when trying to verify its sensor platform
```

**Comment by ludeeus** [comment]
Open an issue with that integration.

**Comment by iantrich** [comment]
And if you uninstalled it, remove it from your configuration

**Comment by circa1665** [comment]
Thanks, already removed from configuration, new issue opened here: https://github.com/custom-components/sensor.plex_recently_added/issues/25#issue-470811203

**Comment by circa1665** [comment]
Thanks, already removed from configuration, new issue opened here: custom-components/sensor.plex_recently_added#25
