### ISSUE TITLE
File is not copied if file name equals folder name

### ISSUE THREAD

**Issue by rgruebel** [custom-components/hacs#321]
## Version of HACS
0.12.1

## Describe the bug
If ha_zigbee2mqtt_networkmap is installed via HACS, the file viz.js (folder name equal to file name) is missing. An archive remains from another file (full.render.js). See screenshot:

![image](https://user-images.githubusercontent.com/1482159/61593235-4c6f5e80-abdd-11e9-967e-6597ec283f70.png)

**Comment by ludeeus** [comment]
Will try to fix that to 0.13.0

**Comment by sebiweise** [comment]
#rgruebel/ha_zigbee2mqtt_networkmap/18

**Comment by sebiweise** [comment]
rgruebel/ha_zigbee2mqtt_networkmap#18
