### ISSUE TITLE
Allow pre-releases in GitHub

### ISSUE THREAD

**Issue by hakana** [custom-components/hacs#322]
When I create a release marked as pre-release in GitHub it shows in HACS as a normal release.

It would be nice if pre-releases not is proposed as the latest release and not show it as available with yellow icon. It should be in the version drop-down marked as "pre-release" but not selected as default. In this way pre-releses can be used by user that want to pre-test the latest release.

I hope you understand what you mean...

**Comment by ludeeus** [comment]
Pre-releases is **only** accessible for the user _if_ he/she has enabled "Beta" from the dropdown menu inside the repository view and does only apply to that repository.

**Comment by ludeeus** [comment]
As an alternative, if you want to display that it is a beta version to the user you could add this to the top of `info.md`

```
{% if prerelease %}
## **NB!** This is a beta/pre-release version!
{% endif %}
```
<https://custom-components.github.io/hacs/developer/general/#enhance-the-experience>

**Comment by hakana** [comment]
Hi Joakim,

Thanks for quick response!

Ok, that sounds good. But for me all repros have “show beta” enabled as default?

Another thing, when I click the “Open issue” it link to wrong page.

https://github.com/ShellyForHASS/issues/

should be:

https://github.com/StyraHem/ShellyForHASS/issues/ maybe with /new in the end.

Best regards
Håkan

Från: Joakim Sørensen <notifications@github.com>
Skickat: den 21 juli 2019 20:13
Till: custom-components/hacs <hacs@noreply.github.com>
Kopia: Håkan Åkerberg <hakan@tarra.se>; Author <author@noreply.github.com>
Ämne: Re: [custom-components/hacs] Allow pre-releases in GitHub (#322)


Pre-releases is only accessible for the user if he/she has enabled "Beta" from the dropdown menu inside the repository view and does only apply to that repository.

**Comment by ludeeus** [comment]
> Ok, that sounds good. But for me all repros have “show beta” enabled as default?

If it say "Sow beta" it will not show the beta, that is an action.
When beta is visible for a repository the same button will say "Hide beta".

As for the issue link, I'll split that into a separate issue and tag it for 0.13

**Comment by hakana** [comment]
Hi Joakim,

Yes, I mean default is that is showning beta and the action in the menu is “Hide beta”.

/Håkan


Från: Joakim Sørensen <notifications@github.com>
Skickat: den 21 juli 2019 20:37
Till: custom-components/hacs <hacs@noreply.github.com>
Kopia: Håkan Åkerberg <hakan@tarra.se>; Author <author@noreply.github.com>
Ämne: Re: [custom-components/hacs] Allow pre-releases in GitHub (#322)


Ok, that sounds good. But for me all repros have “show beta” enabled as default?

If it say "Sow beta" it will not show the beta, that is an action.
When beta is visible for a repository the same button will say "Hide beta".

As for the issue link, I'll split that into a separate issue and tag it for 0.13

**Comment by ludeeus** [comment]
Sounds like the migration have not done what it should <https://github.com/custom-components/hacs/blob/master/custom_components/hacs/hacsbase/migration.py#L90-L98>

There was one version that was not working.
I'll add another migration step for 0.13 to handle this again.
