### ISSUE TITLE
Themes Configuration Error

### ISSUE THREAD

**Issue by seaverd** [custom-components/hacs#329]
I am having an issue with installing themes. 
Running 0.12.1 version of HACs.

Here is pertinent portion of configuration.yaml

frontend:
  themes: !include_dir_named themes
hacs:
  token: mytoken
  theme: true

Under HACs I see one theme, slate.   After installing slate, When I hit the check configuration button in HA I get the following error:

Invalid config for [frontend]: value should be a string for dictionary value @ data['frontend']['themes']['slate']['slate']. Got OrderedDict([('primary-color', '#2980b9'), ('accent-color', '#b58e31'), ('dark-primary-color', '#2980b9'), ('light-primary-color', '#2980b9'), ('primary-text-color', '#FFFFFF'), ('text-primary-color', 'var(--primary-text-color)'), ('secondary-text-color', '#b58e31'), ('disabled-text-color', '#777777'), ('label-badge-border-color', 'green'), ('sidebar-icon-color', '#777777'), ('primary-background-color', '#222222'), ('secondary-background-color', '#222222'), ('divider-color', 'rgba(0, 0, 0, .1.... (See /config/configuration.yaml, line 19). Please check the docs at https://home-assistant.io/components/frontend/  

Restarting HA with the above config throws errors on the frontend and yields no UI.  
If I comment out the following line error goes away, but obviously get no themes.

#  themes: !include_dir_named themes

Should HACs be installing the slate.yaml file in a folder named slate?   Currently the theme folder just contains one file named slate.yaml (no subfolders).   Please note to date I have never installed/used themes.

Thanks,
Dan

 Before you open a new issue, search through the existing issues to see if others have had the same problem.

Issues not containing the minimum requirements will be closed:

- Issues without a description (using the header is not good enough) will be closed.
- Issues without debug logging will be closed.

-->

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
Use the include method as described here and it will work <https://custom-components.github.io/hacs/faq/#files-downloaded-for-theme>

```
frontend:
  themes: !include_dir_merge_named themes
```
