### ISSUE TITLE
Does not refresh after updates

### ISSUE THREAD

**Issue by RichardUUU** [custom-components/hacs#343]
## Version of HACS
0.12.1

## Describe the bug

Not a big issue, but ...
After updating a card, the browser continues to show that an update is required. Even refreshing the browser does not show the updated status. Only way to show that the card is updated is to exit back to the Overview.

## Debug log

Should be replicable on any system.

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
It is not replicable on any system, I do not see it, I know one more have had this issue when accessing though a proxy, it is the service worker in the browser that serves a cached version of the page.
Should be fixed in the next version.
