### ISSUE TITLE
New Section or New releases Area 

### ISSUE THREAD

**Issue by holdestmade** [custom-components/hacs#350]
**Is your feature request related to a problem? Please describe.**
Could we have "New" section at the top or new release area at the top in the store ?

**Describe the solution you'd like**
A "New" section or new release at the top ?

**Describe alternatives you've considered**
na

**Additional context**
na

**Comment by ludeeus** [comment]
**_If_** you are talking about something like this, that will **only** show _if_ you have at least one new item, then yes that is doable.

obviously, this will **only** be for the store.

![image](https://user-images.githubusercontent.com/15093472/62217697-63ffd180-b3ab-11e9-9490-b5497fd0c3ae.png)

**Comment by holdestmade** [comment]
Yes that looks great, not sure if you need the word repositories though, Just NEW (ALL) would look ok as it's new items not repos
Cheers

**Comment by ludeeus** [comment]
I would like to keep the configuration to a minimum.
