### ISSUE TITLE
More accessible links to repos

### ISSUE THREAD

**Issue by kloggy** [custom-components/hacs#357]
Would it be possible to put a link to the repository of the integration/plugin on the Overview page?

Ok, so it's not a big deal but every time I want to look up how a plugin works it would be nice to get to the repo more quickly.

Like I said, only a small request but if it is as simple as it sounds then it shouldn't be a problem but if it isn't practical then no worries....

**Comment by ludeeus** [comment]
ideally, the developer would add info.md file to the repo with that information (that will be displayed in the repository view, that way the number of clicks will be the same as if it was on the overview, and the overall experience would be better.

I may add a "full" / "preview" / "something" view in addition to "grid" and "table" that are there now, but that is something for the future, and not really what you are asking here.

Adding a link (or really anything) to the current views is not something I will do (those should be minimalistic.)
