### ISSUE TITLE
alphabetical  order

### ISSUE THREAD

**Issue by vMeph** [custom-components/hacs#36]
would be nice to have all entry to be in  alphabetical order

CUSTOM PLUGINS (LOVELACE)
CUSTOM INTEGRATIONS
CUSTOM INTEGRATION REPOSITORIES
CUSTOM PLUGIN REPOSITORIES

right now when you add card etc, they all show in order of installation, would be nice to have them re arrange in alphabetical order

**Comment by ludeeus** [comment]
This was included in the [`0.5.0` release](https://github.com/custom-components/hacs/releases/tag/0.5.0)
