### ISSUE TITLE
Requirements handling for AppDaemon apps

### ISSUE THREAD

**Issue by benleb** [custom-components/hacs#376]
**Describe the solution you'd like**
Automatic download/install of requirements of appdaemon apps **and** also showing them directly in the UI to at least to know which packages would be installed if one clicks on "INSTALL". Maybe also just allow requirements with a pinned version.
The typical way with a requirements.txt file shipped in the same dir as the app would be nice. Probably we should also think about separate venvs for each app or another/smaller way of "isolation". There could be incompatible requirements (other versions of package XY for example) which cause strange effects or worse.

**Describe alternatives you've considered**
Ship the requirements itself within the app. This would require to also check in all required packages into the apps repo... I think its self explaining this way sucks...

Ben

**Comment by benleb** [comment]
Hmmm it seems AppDaemon itself installs them if the requirements.txt is in the root of the repo. But no isolation or other kind of separating the requirements of different apps...

**Comment by ludeeus** [comment]
I've looked into this, and from HACS this will not be possible.

For hassio/docker AD are in a seperate container.
For other installations, AD _should_ be in a different venv then HA (HACS)

**Comment by benleb** [comment]
Yes, AD/Hass is seperate... But imagine the following scenario...

A user has installed appXY which hast **libraryXY==0.8.2** as requirement. Now the user installs appZT which requires **libraryXY==0.9.5** -> appXY may break.

I am not sure how to solve this in a clean fashion but it seems like a real issue from my perspective

**Comment by ludeeus** [comment]
Yes, but HACS does not have access to the env for AD, so that is not something that HACS can solve.

**Comment by benleb** [comment]
Ahm okay? And the solution is "we hope no user ever install two apps with conflicting requirements"? Maybe HACS could (should?) at least parse the requirements and show a warning or something?

And, this is not specific to AppDaemon, its the same case for components/integrations for Home Assistant.

**Comment by ludeeus** [comment]
pip handles that (or at least it should), it _should_ give an error if you try to change a version of a lib that is pinned.

And generally parsing/controlling of that is out of the scope of this FR (and probably something that will not happen in HACS)

Home Assistant/AD/pip should be responsible for that.
