### ISSUE TITLE
0.13.0 Beta issues

### ISSUE THREAD

**Issue by ludeeus** [custom-components/hacs#377]
Post all issues related to the beta here.

**"Rules" for posting.**

_This will keep the thread tidy._

- Use hastebin (or similar) to post logs.
- Use imgur (or similar ) to post picures.

**Comment by Bluhme1** [comment]
Think I did everything as described, but cannot see Hacs on the sidebar.
Log says:

Error setting up entry  for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 153, in async_setup
    hass, self)
  File "/config/custom_components/hacs/__init__.py", line 88, in async_setup_entry
    startup_result = await hacs_startup(Hacs)
  File "/config/custom_components/hacs/__init__.py", line 121, in hacs_startup
    if not check_version(hacs):
  File "/config/custom_components/hacs/__init__.py", line 193, in check_version
    hacs.logegr.critical(
AttributeError: type object 'Hacs' has no attribute 'logegr'

**Comment by benleb** [comment]
> Think I did everything as described, but cannot see Hacs on the sidebar.
> Log says:
> 
> Error setting up entry for hacs
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/config_entries.py", line 153, in async_setup
> hass, self)
> File "/config/custom_components/hacs/**init**.py", line 88, in async_setup_entry
> startup_result = await hacs_startup(Hacs)
> File "/config/custom_components/hacs/**init**.py", line 121, in hacs_startup
> if not check_version(hacs):
> File "/config/custom_components/hacs/**init**.py", line 193, in check_version
> hacs.logegr.critical(
> AttributeError: type object 'Hacs' has no attribute 'logegr'

fixed in #378

**Comment by ludeeus** [comment]
Will have a looks at the PR egen i her Home.
But it Will not fix the startup issue, you only get to that point if HA version is < 0.97

**Comment by VDRainer** [comment]
Successfully installed and configured using config_flow.
The beta HACS shows the old HACS 0.12.1 as integration.
Shouldn't that be removed?
If so, how?

**Comment by ludeeus** [comment]
@VDRainer I have no clue what you are talking about 🙈 where do you see that?
How is it displayed?

**Comment by VDRainer** [comment]
HACS -> Settings (0.13.0b0)
http://pix.toile-libre.org/upload/original/1564946305.png
HACS -> Overview Integrations (0.12.1)
http://pix.toile-libre.org/upload/original/1564946381.png

**Comment by ludeeus** [comment]
Cool!
Not sure how to fix that, but will look into it.

**Comment by Stephan296** [comment]
I dont see him in the menu at the left side.
logfile:

> 2019-08-04 21:14:33 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for hacs
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 153, in async_setup
>     hass, self)
>   File "/config/custom_components/hacs/__init__.py", line 88, in async_setup_entry
>     startup_result = await hacs_startup(Hacs)
>   File "/config/custom_components/hacs/__init__.py", line 121, in hacs_startup
>     if not check_version(hacs):
>   File "/config/custom_components/hacs/__init__.py", line 193, in check_version
>     hacs.logegr.critical(
> AttributeError: type object 'Hacs' has no attribute 'logegr'

**Comment by ludeeus** [comment]
@Stephan296 You have a too old HA version, as stated in the releasenotes you **need** HA version 0.97+

**Comment by Stephan296** [comment]
oopssssss..... shame on me! I update now my other HA to 0.97 beta. Sorry!

**Comment by VDRainer** [comment]
Got another one.
On config_flow there are checkboxes to lookup appdaemon apps, python_scripts and themes.
How do i add/change them after setup is complete?
There's nothing to edit in Configuration -> Integrations -> HACS

**Comment by DavidFW1960** [comment]
![image](https://user-images.githubusercontent.com/36390762/62433733-0091ed00-b779-11e9-896f-5b20a8698833.png)
So same as VSRainer... I did select it to show betas and HACS 13.1 is installed via an integration but old info showing in the overview. Also wondering how to change the integration settings later after it has been added.

**Comment by ludeeus** [comment]
Integrations can not be changed.
You need to remove it, the re add it.

**Comment by ludeeus** [comment]
B1 released <https://github.com/custom-components/hacs/releases/tag/0.13.0b1>

**Comment by DavidFW1960** [comment]
‘The frontend of HACS have been disabled until you restart Home Assistant’

Huh? I have it as an integration and not in config yaml anymore..... wasn’t not needing to restart the reason for it being an integration?

**Comment by ludeeus** [comment]
Yes and no.
For initial installation and configuration you don't need restart, for upgrades you still do.

**Comment by DavidFW1960** [comment]
So I don’t see any benefit of it being an integration.

**Comment by r3mcos3** [comment]
i'm missing some icons in the overview page 
in grid and table view.

![missingicons](https://user-images.githubusercontent.com/45529818/62526232-267ec680-b839-11e9-88a5-b792af4801de.jpg)

**Comment by bussio** [comment]
Since the v0.13.0b0 I have a problem with the integration "Sensor.Geoip". If I remove them with "uninstall", then the folder "None" under "custom_components" will be removed, but after a reboot this appears again in the overview with the status "Orange".

**Comment by ludeeus** [comment]
@r3mcos3 any errors in your browser console?
if not, try clearing the cache

**Comment by ludeeus** [comment]
@DavidFW1960 now there are not much for HACS it self (You can "hot change" settings, but that's it).
For integrations installed with HACS you can see an integration you like install it (and if it supports config_flow) set it up without restarting.

Conflig_flows are missing the ability to edit, and you need to restart for updates.
Maybe that will be added in a later version of HA, who knows 🤷‍♂

**Comment by ludeeus** [comment]
@bussio That sounds wierd, there should not be a "None" folder there....

**Comment by r3mcos3** [comment]
these are the errors i have 
![2019-08-06 18 36 36 10 10 50 90 468f017f1bea](https://user-images.githubusercontent.com/45529818/62558442-5948af00-b879-11e9-87b4-72454c8968b8.jpg)

**Comment by ludeeus** [comment]
That would be it, try reinstalling the "next" or "0.13.0b1" version

**Comment by bussio** [comment]
> @bussio That sounds wierd, there should not be a "None" folder there....

I meant the folder, which is mentioned here in the description of the integration under HACS.
"When installed, this will be located in '/ config / custom_components / None', you still need to add it to your 'configuration.yaml' file."

**Comment by ludeeus** [comment]
@bussio moved your issue to #384

**Comment by DavidFW1960** [comment]
So the other day I clicked on the  mark all as not new anymore button in the store and since then I don't see ANY new items? I also see hacs.4 file seems to show a lot of 3
```
"new": true
```
So there must be new items?

**Comment by DavidFW1960** [comment]
are the files..
.storage/hacs.4
.storage/hacs.none
old files no longer used that I can delete?

**Comment by ludeeus** [comment]
With numbers are backups, if you have upgraded and everything is working they can be removed

**Comment by DavidFW1960** [comment]
I have deleted the number ones before... but the new beta seems to not use the hacs file anymore - it seems to use hacs.repositories as a replacement and there is also hacs.hacs and hacs.installed - I assume no one should touch any of those. Also assume hacs.none can be safely deleted as well?

I think I might have been pending a restart and that was why I wasn't seeing anything new. After I installed the 0.97.0b3, HACS then showed a new item again and I could click on the button to clear - then after a restart it hasn't come back and I don't see any with "new": true anymore - so is that the correct way? Does the hacs.repositories only get refreshed (and the flag set to "new": false when HA is restarted) after you tap the mark button?

**Comment by r3mcos3** [comment]
> That would be it, try reinstalling the "next" or "0.13.0b1" version

The "next" fixed the problem

**Comment by bussio** [comment]
After the update of the integration "Alexa Media Player" and the plugin "Weather Card" I always got a red bar at the end with the following message "'NoneType' object has no attribute 'display_version_or_commit'.
(hass.io 0.97, hacs 0.13.0b1)

**Comment by owendemooy** [comment]
I am having an issue with all versions of HACS this is my first time using it. I have tried 0.12 and now 0.13 beta

I can setup the integration correctly with the API key etc but when I click the Community icon on the side bar the main view displays an error <baseurl> refused to connect

I can't find anyone else with this error. I am running docker version of HASS behind a traefik proxy if that helps.

**Comment by ludeeus** [comment]
@owendemooy https://github.com/custom-components/hacs/issues/87

**Comment by ludeeus** [comment]
@DavidFW1960 HACS will remove those files eventually itself.
As for the clear button, I saves when it's done <https://github.com/custom-components/hacs/blob/next/custom_components/hacs/api.py#L96>

**Comment by ludeeus** [comment]
I'm not able to reproduce that issue  @bussio please open a new issue here and add your debug logs to it.

**Comment by bussio** [comment]
@ludeeus I can not understand it either, after the mentioned restart the error did not occur anymore.

**Comment by ludeeus** [comment]
Oh so you do not see it anymore?

**Comment by r3mcos3** [comment]
new update breaks all plugins & integrations 
a simpel reinstall off the plugin or integration or hacs itself doesn't work!
![2019-08-10 13 01 06 10 10 50 90 de0421ce15c8](https://user-images.githubusercontent.com/45529818/62821062-f011b600-bb6e-11e9-8a5b-d1551e18f330.jpg)

**Comment by ludeeus** [comment]
Your HACS did not start properly, check your logs

**Comment by bussio** [comment]
> Oh so you do not see it anymore?

In the newest v0.13.0b2 everything works so well. Also the entry "sensor.geoip" is not listed in the overview and in the store after another uninstall / restart. Thanks for that!

**Comment by DavidFW1960** [comment]
Running B3, isn't the sensor supposed to have attributes?
![image](https://user-images.githubusercontent.com/36390762/62829142-5f081100-bc3a-11e9-80c3-277fd07c4b50.png)
With versions etc? Or am I misreading the release notes?

**Comment by ludeeus** [comment]
Only when there is pending updates
