### ISSUE TITLE
scrollbar request

### ISSUE THREAD

**Issue by vMeph** [custom-components/hacs#38]
would be nice to have a scroolbar
![1](https://user-images.githubusercontent.com/12812111/58759210-4d114000-851e-11e9-9a95-7907fded187d.png)

**Comment by ludeeus** [comment]
If you find one that works (and does not look like it was taken from 1994) please add it :)

**Comment by bonzai86** [comment]
With your manual hack, you break scrolling in lovelace etc.
Looks like the [iframe](https://github.com/home-assistant/home-assistant-polymer/blob/bbae3291e1187e764088bdbbc28e95d3e20382d1/src/panels/iframe/ha-panel-iframe.js#L15) is to big and the scroll bar is visible.

**Comment by ludeeus** [comment]
This has been corrected in [`0.4.4`](https://github.com/custom-components/hacs/releases/tag/0.4.4)
