### ISSUE TITLE
Multiple custom_components in a single repository?

### ISSUE THREAD

**Issue by rsnodgrass** [custom-components/hacs#385]
I searched and couldn't find anything in the documentation or previous issues about this.  I suspect I missed something obvious. 

I have multiple custom components in a repository, but only one of them appears in HACS, any ideas:

   https://github.com/rsnodgrass/hass-integrations/

## Version of HACS 0.12.1

**Comment by ludeeus** [comment]
<https://custom-components.github.io/hacs/developer/integration/#repository-structure> 
See the first requirement there ;)
