### ISSUE TITLE
HACS 0.12.1 component does not load

### ISSUE THREAD

**Issue by tyfoon** [custom-components/hacs#387]
I’m having problems installing HACS (eg get the component loaded correctly in HASS).

What I have done (I’m on HASSIO 95.6):

- Followed instructions by the letter (I also have several customer components already) and double checked if all files are there / not corrupted
- Removed any old ‘customer updater’ stuff from file system & configuration.yaml (left the stuff in Lovelace).
- Used ‘latest’ link (0.12.1) for HACS files
- I have created Github API key successfully and have tried restarting several times with and without the entry below

```
hacs:
  token: xxxxxxxxxxxxxxxxxxxxxxxxx
```

HASS starts but I get notification that HACS could not be set up with below in logs

## Debug log
2019-08-07 23:13:28 ERROR (MainThread) [homeassistant.setup] Error during setup of component hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 153, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/hacs/__init__.py", line 61, in async_setup
    from .aiogithub.exceptions import AIOGitHubAuthentication, AIOGitHubException, AIOGitHubRatelimit
ModuleNotFoundError: No module named 'custom_components.hacs.aiogithub.exceptions'

**Comment by ludeeus** [comment]
Make sure you download all the files.
You are at least missing this https://github.com/custom-components/hacs/blob/0.12.1/custom_components/hacs/aiogithub/exceptions.py

**Comment by tyfoon** [comment]
This made me double check all files. And indeed this file was missing. Strange as I just copied the whole hacs directory with all its files over.

So this did it and all working fine. Thanks
