### ISSUE TITLE
HACS not loading anymore with error Restore Failed! 

### ISSUE THREAD

**Issue by simonblaster** [custom-components/hacs#389]
Hi,
I have an issue with HACS in Hassio v 0.97.
Since yesterday, it is not loading anymore without notifying any problem, the "community" tab do not show up and the logs report an critical issue "Restore Failed": number of installed repositories do not match the number of restored repositories.
Find the related log here:

![image](https://user-images.githubusercontent.com/46835101/62763331-8ff61380-ba8b-11e9-9838-f0df3dc607bc.png)
Any help would be highly appreciated.
Thanks,
Simone

**Comment by ludeeus** [comment]
That is a known issue in b1.
Download the latest `next` version https://github.com/custom-components/hacs/archive/next.zip

**Comment by simonblaster** [comment]
Thanks,
I was searching for similar cases but could not find any.
To change the version, shall I replace the HACS folder in my home assistant custom component folder with the one in the zip?

**Comment by ludeeus** [comment]
with "known" I meant that I have seen it in my dev setup :P 

Yes, just replace the folder and restart HA.

**Comment by simonblaster** [comment]
Perfect, I followed your indications and it now works again.
Thanks a lot for your immediate help.
Cheers,
Simone
