### ISSUE TITLE
Path consistency for custom cards

### ISSUE THREAD

**Issue by tmechen** [custom-components/hacs#390]
## Version of HACS
0.12.1

## Describe the bug
Path for custom Cards is not consistent, its displaying "community-plugins" for path to add to the configuration, but is actually just "community" 
![Screenshot 2019-08-09 at 17 33 22](https://user-images.githubusercontent.com/9123876/62790966-817c1c00-bacc-11e9-9726-ad304323d6e4.png)

**Comment by ludeeus** [comment]
This is not correct.
`/community_plugin/` is the correct endpoint for this.

**Comment by tmechen** [comment]
uhm... for me it installed to www/community/XY
anyway, if its community_plugin, then the text above should be changed

**Comment by ludeeus** [comment]
No, you are mixing to different things.

The location on the filesystem is www/community/*, but the URL (endpoint you use) is /community_plugins/*

**Comment by tmechen** [comment]
ohhhhhh now i see, my cache did hold the old versions, therefore it didnt fail for me after reinstalling. okay, sry, then everything is fine :) nice work! thx
