### ISSUE TITLE
Support bare folder home assistant custom components

### ISSUE THREAD

**Issue by elupus** [custom-components/hacs#402]
**Is your feature request related to a problem? Please describe.**
Allowing support for raw custom component repo would allow repo's designed for use with for example git submodules inside custom_components or just checkout of custom component directly from git to be interoperable with HACS repos.

The way to use such repo's without HACS is:
```
cd custom_components
git checkout https://github.com/elupus/hass_nibe nibe
```

**Describe the solution you'd like**
Support a repository structure where the home assistant integration resides at the root of the git repo like: https://github.com/elupus/hass_nibe.

There is no need to necessarily support a git checkout. It should be enough to still use zip archives of the repo.

**Describe alternatives you've considered**

**Additional context**

**Comment by ludeeus** [comment]
Depends on #338 
Could potentially be "flagged" to hacs with a `"files_in_root": True,` key

**Comment by ludeeus** [comment]
Added support for this in <https://github.com/custom-components/hacs/releases/tag/0.14.0b0>

https://beta--hacs.netlify.com/developer/general/#hacsjson `content_in_root`
