### ISSUE TITLE
Issue with info.md templating

### ISSUE THREAD

**Issue by gadgetchnnel** [custom-components/hacs#404]
## Version of HACS
0.13.0

## Describe the bug
Template text on the info.md file is sometimes displaying as plain text and not being templated. For example:

![Screenshot 2019-08-11 at 20 39 21](https://user-images.githubusercontent.com/2099542/62838964-26d4f280-bc7b-11e9-8e10-3cb23be69ebe.png)

When selecting "next" from the drop-down, it applies the template as expected and only displays the text saying that it is the development version.

No error messages appear in the log.

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
Only sometimes?
How are you running Home Assistant?

**Comment by gadgetchnnel** [comment]
@ludeeus It actually appears to happen consistently, but only for certain releases. For example, the HACS integration shows the issue when version **0.13.0** is selected (as in the screenshot) but not when **next** is selected.

I am running Home Assistant in Raspbian (virtual environment) on a Raspberry Pi 3 B+

**Comment by ludeeus** [comment]
How "fun" at this point that file is _identical_ for `0.13.0` and `next` :/

**Comment by jaxc0402** [comment]
same here!!

**Comment by ludeeus** [comment]
And you also run in a venv?

**Comment by jaxc0402** [comment]
running home assistant on a rasp Pi 2B direct via https://www.home-assistant.io/blog/2017/07/25/introducing-hassio/

**Comment by gadgetchnnel** [comment]
Interestingly, I just updated HACS to 0.13.1 and now, I see this if 0.13.1 is selected from the dropdown:

![Version-0 13 1](https://user-images.githubusercontent.com/2099542/63038961-33935980-beba-11e9-9d4f-51352b9a8c69.png)

but when 0.13.0 is selected it displays correctly like this:

![Version-0 13 0](https://user-images.githubusercontent.com/2099542/63038996-460d9300-beba-11e9-88c2-bf8fca7cd8da.png)

The templating issue was happening previously when 0.13.0 was selected, but not for other versions, so it looks like I am seeing this issue when the version in the dropdown is the same as the currently installed version. 

I have templating in the info.md file on one of my plugins, and I'm not seeing the same issue there, so could this be an issue which just affects integrations, or maybe even just just the HACS integration in particular?

**Comment by ludeeus** [comment]
From what I can tell if only applies to HACS itself, it will be removed in the next version effectively "fixing" this issue

**Comment by ludeeus** [comment]
Fixed in https://github.com/custom-components/hacs/releases/tag/0.13.2
