### ISSUE TITLE
HA not run when add configuration

### ISSUE THREAD

**Issue by pepeEL** [custom-components/hacs#41]
I try this on my HA. Before use custom updater. But delete it. 
I done all with manual installation and when add to my configuration.yaml config with tokens and reboot my HA, after Home Assistant not running. 
When remove from config running ok.

**Comment by ludeeus** [comment]
python 3.5?

**Comment by TorqueDelight** [comment]
For my part, I cannot restart HA, I get the folowing error on the config check :
`Configuration invalide
Component not found: hacs`

**Comment by ludeeus** [comment]
that is not relevant open a separate issue (or better just restart (**not** from UI) @TorqueDelight

**Comment by ludeeus** [comment]
https://github.com/custom-components/hacs/releases/tag/0.4.3 fixes your issue @pepeEL , you should also look into upgrading python :)
