### ISSUE TITLE
Store show already cards installed

### ISSUE THREAD

**Issue by vMeph** [custom-components/hacs#42]
would be nice to when searching on store section for new cards that would show on the side of ``MORE INFO`` like something saying `` Installed or Unistall`` for we can see witch cards we already have installed, another option could be the cards that are already installed  would disappear from store section sense they show up in overview

**Comment by ludeeus** [comment]
I want to remove the link area in overviews #40 
Maybe a special icon, could be added, I will not hide them from it.

**Comment by vMeph** [comment]
i like the idea

**Comment by ludeeus** [comment]
I'm closing this since it's by now the same as #15
