### ISSUE TITLE
Missing migration step for 1 - 4

### ISSUE THREAD

**Issue by Bram1nat0r** [custom-components/hacs#432]
I have removed custom_component/hacs directory and installed the latest hacs (0.13.0).
Also I have renamed the community folder (/config/www/community) with existing custom elements; so I have tried to do a clean install.

Now I keep getting :

Missing migration step for 1 (CRITICAL)
Missing migration step for 2 (CRITICAL)
Missing migration step for 3 (CRITICAL)
Missing migration step for 4 (CRITICAL)

The Community link in the Side Panel doesn't show up.

What am I doing wrong, or is this a bug?

Thanks

**Comment by ludeeus** [comment]
Looks like I have misconfigured my bot :(

You can find the answer here https://github.com/custom-components/hacs/issues/416
