### ISSUE TITLE
[Expecting value: line 1 column 1 (char 0)] Restore Failed!

### ISSUE THREAD

**Issue by uspino2** [custom-components/hacs#433]
Upgraded to HACS 0.13 and getting 

```
[Expecting value: line 1 column 1 (char 0)] Restore Failed!
8:34 AM custom_components/hacs/hacsbase/data.py (CRITICAL)
```

HACS does not show on side bar. Worked fine before upgrade.

**Comment by ludeeus** [comment]
Set logging to debug, and share the _entire_ startup progress.

**Comment by ludeeus** [comment]
Looking at your minimal info here.
The issue is probably that one (or more) of the files containing `hacs` under `/config/.storage` are empty.

**Comment by uspino2** [comment]
I have these 4 has files in .storage:

```
hacs.4
hacs.hacs
hacs.installed
hacs.repositories
```

Are you referring to those files?

**Comment by ludeeus** [comment]
yes

**Comment by uspino2** [comment]
Ok deleting those 4 files before reinstalling did the trick, it's working again. I lost my list of watched components/pulgins etc. Is there a way I can extract that from a backup?

**Comment by ludeeus** [comment]
Possible yes.
Easy, no.

If you have a backup of the `hacs.4` file:
stop HA.
delete all `hacs` files under `.storage`
place the `hacs.4` file in `.storage`
rename that file from `hacs.4` to `hacs`
Start HA.

**Comment by uspino2** [comment]
That worked, thanks!
