### ISSUE TITLE
HACS may have deleted python_scripts it doesn't manage

### ISSUE THREAD

**Issue by dlashua** [custom-components/hacs#434]
## Version of HACS

0.13.0

## Describe the bug

It's possible that HACS deleted my python_scripts. I have a bunch of python_scripts that are not managed by HACS and only one that is. Yesterday I upgraded the one that is (shellies discovery) through HACS, and then didn't give it a second thought. Today I realize something is acting weird with a python_script and I go to check it out and everything is gone except for shellies_discovery.py.

I have a back up. Everything is fine now. And I don't have logging on to any degree of usefulness to give you proper information. So it's just a heads up

## Debug log

```text

No useful logs. 

```

**Comment by ludeeus** [comment]
Will check when I get home.

**Comment by ludeeus** [comment]
Confirmed.

**Comment by ludeeus** [comment]
Fixed in 0.13.1 https://github.com/custom-components/hacs/releases/tag/0.13.1
