### ISSUE TITLE
Css issue with custom repo on mobile

### ISSUE THREAD

**Issue by ljmerza** [custom-components/hacs#439]
![Screenshot_20190815-174018_Chrome](https://user-images.githubusercontent.com/4085765/63128794-e24f9c80-bf83-11e9-8ef1-94434efadfed.jpg)

## Version of HACS
Latest

## Describe the bug
On mobile the dropdown menu is really small and not aligned as well as the input for custom repo

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
Fixed in https://github.com/custom-components/hacs/releases/tag/0.13.2
