### ISSUE TITLE
HACS community icon missing. sensor.hacs not available

### ISSUE THREAD

**Issue by TomBrandt** [custom-components/hacs#443]
HACS installed ok Home assistant is installed VMbox Ubuntu 64, Hassio Intel Nuc VMDK. 
hass.io supervisor version 178. hassos version 2.12 and HACS 13.01.
Community icon was there. Also I was able to install wyze.sense. Which was the reason for this effort. I no longer see the community side bar icon. 
Added option to configuration file for side_bar: true No help.
Debug log partial:
INFO (MainThread) [hacs.repository.integration.custom-components.hacs] Registration complete
2019-08-16 07:34:27 CRITICAL (MainThread) [hacs.data] [Expecting value: line 1 column 1 (char 0)] Restore Failed!
2019-08-16 07:34:27 INFO (MainThread) [hacs] Could not setup HACS, trying again in 15 min
Issues not containing the minimum requirements will be closed:

[home-assistant.log](https://github.com/custom-components/hacs/files/3510054/home-assistant.log)

```

**Comment by ludeeus** [comment]
Delete all the files containing `hacs` under `.storage` one (or more of them) are missing content.

**Comment by TomBrandt** [comment]
thanks. but background task running forever?
