### ISSUE TITLE
info.md is not rendered properly when containing "risky text"

### ISSUE THREAD

**Issue by astrandb** [custom-components/hacs#450]
## Version of HACS
13.2

## Describe the bug
The text below is copied from info.md for the favicon changer custom component. The rendering in HACS is wrong from  ` <your ` and onwards.
```text
- Copy the contents of `custom_components/favicon/` to `<your config dir>/custom_components/favicon/`.
```
I have tested a couple of browsers and they all give slightly different results, but none is correct.
It is probably easy to avoid this bug by a minor change in the actual info.md. However, I think the bug should be wiped out so it does not reappear in a new place.

**Comment by ludeeus** [comment]
This is actually not a bug, the developer is free to add custom things like html to those files.
Which is (probably unintentionally) done here.

`<your` is interpreted as a custom html tag, and the browser will try to display is as that.

**Comment by ludeeus** [comment]
Handled in <https://github.com/custom-components/hacs/releases/tag/0.14.0b0> with new render logic.
