### ISSUE TITLE
Integration not found after upgrading

### ISSUE THREAD

**Issue by 335iguy** [custom-components/hacs#457]
## Version of HACS
0.94

## Describe the bug
This was a "read the breaking changes before you break things" moment.
Linux Mint VM on Proxmox using Docker

In HA 0.93.x, I upgraded HACS on the frontend and got error messages saying that I needed to upgrade HA. Upgraded HA from 0.93.x to 0.97.x and still had issues. 

Removed HACS from configuration.yaml and HA would present
`ERROR (MainThread) [homeassistant.setup] Setup failed for hacs: Integration not found.`

Removed both the HACS folder in /custom_components parent folder and the /community folder in /www parent folder. Restarted with same error.

Went searching in file system for anything related to HACS and found a file in /.storage. Removing that yielded no results.

grep'd "hacs" in my entire config directory and found a line in `core.config_entires` json file that represented HACS. Deleted the json content related to HACS and the error message was gone.

## Debug log

```text

ERROR (MainThread) [homeassistant.setup] Setup failed for hacs: Integration not found. 

```

**Comment by ludeeus** [comment]
```
Setup failed for hacs: Integration not found.
```

You get this when you are missing required files, redownload from the latest release and folow the instructions.

- https://github.com/custom-components/hacs/releases/latest
- https://hacs.netlify.com/installation/manual/

**Comment by Tokynet** [comment]
@335iguy did this fix it for you? i'm still not able to start it.
