### ISSUE TITLE
Hassio stopps responding when trying to access HACS

### ISSUE THREAD

**Issue by Nseerr** [custom-components/hacs#460]
## Describe the bug

When trying to open the HACS page, from were you can update and so, I lose the connection to Hassio.

![Skärmklipp](https://user-images.githubusercontent.com/51890041/63259458-c0edf980-c27e-11e9-9a05-0d90fe0176a4.PNG)
 

I get the same thing when choiceing upgrade all from settings page, HACS is the only thing not updated. 

![Skärmklipp](https://user-images.githubusercontent.com/51890041/63259676-56898900-c27f-11e9-90ea-6ee8015f7eac.PNG)

## Debug log

```
Could not find anything related to this in the log.  

```

**Comment by ludeeus** [comment]
> Could not find anything related to this in the log.  

Without logs, I can not do anything.

_NB: In the near future, issues without logs will be autoclosed_

**Comment by Nseerr** [comment]
I did a manually reinstalled HACS and now it is working. Not sure if there were some problem that it wanted to update to 0.13.3 when highest available version is 0.13.2.
