### ISSUE TITLE
'custom_components.hacs.http.HacsWebResponse object' has no attribute 'store'

### ISSUE THREAD

**Issue by bieniu** [custom-components/hacs#471]
## Version of HACS
0.13.2

## Version of HA
0.97.2

## Describe the bug
If integration in `manifest.json` contains:
```
{
    "homeassistant": "0.98.0"
}
```
and HA version is below 0.98 (for example 0.97.2) HACS doesn't show integration page but error `'custom_components.hacs.http.HacsWebResponse object' has no attribute 'store'`
![6d8a48b3fbc72bf30122bc45089f9e4a4c96bbeb](https://user-images.githubusercontent.com/478555/63531774-8481fe00-c509-11e9-8d9c-cb2568e3a8ba.png)

## Debug log
No error in log.

**Comment by ludeeus** [comment]
Three news types.

Good: I have already fixed this in master, should be easy to cherry-pick it into a new patch release.
Moderate: Starting with 0.14, that "homeassistant" key should be moved to [`hacs.json`]() I will try to keep legacy options as long as I can (within reason) so will probably be valid until 0.16/0.17/1.0 of HACS
Bad: I'm not sure when I will get the time to push a fix for this, if I don't get it out later today it wil probably not be until sat/sun.

**Comment by bieniu** [comment]
Thanks for your help. I removed this new release. It may wait to HA 0.98 stable release. I will add `hacs.json` files to my repositories.

**Comment by ludeeus** [comment]
Handled in <https://github.com/custom-components/hacs/releases/tag/0.14.0b0>
