### ISSUE TITLE
Not Loading

### ISSUE THREAD

**Issue by brama1966** [custom-components/hacs#476]
[Expecting value: line 1 column 1 (char 0)] Restore Failed!
11:51 AM custom_components/hacs/hacsbase/data.py (CRITICAL)
I checked and it exactly how its supposed to be
even replaced the whole hacs folder with a fresh download

**Comment by ludeeus** [comment]
the issue is with the files containing `hacs` in the `.storage` folder.
Delete all hacs files there.

**Comment by jaxc0402** [comment]
> A warning to anyone applying the aforementioned fix, deleting the `hacs` files in the `.storage` folder will effectively reset your HACS installation. All configured integrations and plugins will have to be manually reconfigured. If you've arrived at this point, there isn't much more you can do but it's better to know before hand than to be surprised after the fact.

where can I find this folder on Hassio??

**Comment by pico563** [comment]
A warning to anyone applying the aforementioned fix, deleting the hacs files in the .storage folder will effectively reset your HACS installation. All configured integrations and plugins will have to be manually reconfigured. If you've arrived at this point, there isn't much more you can do but it's better to know before hand than to be surprised after the fact.

- # where can I find this folder on Hassio??

**Comment by dcbosman** [comment]
I am still struggling with this one.  While installing, icon is showing up, but once installed and going back to main screen, it disappears.  Alos, in .storage, I do not see any hacs files
