### ISSUE TITLE
Include repository display names in sensor.hacs repositories attribute

### ISSUE THREAD

**Issue by gadgetchnnel** [custom-components/hacs#477]
**Is your feature request related to a problem? Please describe.**
The **repositories** attribute of the HACS sensor just contains the repository path rather than the display name (e.g. "keatontaylor/alexa_media_player" rather than "Alexa Media Player"). This makes it difficult to create a nicely formatted card in Lovelace with the details.

**Describe the solution you'd like**
Include both the repository name as well as the path in the **repositories** attribute (maybe keep **name** as it is now and have the name in a property like **display_name**).

**Describe alternatives you've considered**

**Additional context**
A screenshot of what I see when I use the sensor in my Home Feed card

![Screenshot 2019-08-24 at 10 03 49](https://user-images.githubusercontent.com/2099542/63635114-a4730800-c656-11e9-8156-a79eb0681fce.png)

With this extra property it could look more like this (mocked up):

![Screenshot 2019-08-24 at 10 05 45](https://user-images.githubusercontent.com/2099542/63635133-dd12e180-c656-11e9-9aef-aa33b183db6b.png)

**Comment by ludeeus** [comment]
Added in <https://github.com/custom-components/hacs/releases/tag/0.14.0b0>
