### ISSUE TITLE
Filter by location

### ISSUE THREAD

**Issue by nickrout** [custom-components/hacs#483]
**Is your feature request related to a problem? Please describe.**
I don't care when rubbish is being collected in Holland or what new beers are available in Sweden

**Describe the solution you'd like**
Filter out stuff that are not relevant to me/my location

**Describe alternatives you've considered**
This would require developers to have some sort of file describing what countries/continents. Perhaps these could also be meta, ie eu would include all the countries in Europe whereas uk would only include the United Kingdom (bad example perhaps, are they really European any more?)

**Comment by ludeeus** [comment]
That is implemented with the locale tag in the hacs.json file, and filter options will be in 0.14

**Comment by nickrout** [comment]
Superb.

**Comment by ludeeus** [comment]
Added support for this in <https://github.com/custom-components/hacs/releases/tag/0.14.0b0>

**Comment by nickrout** [comment]
:)
