### ISSUE TITLE
problem with amazon.de

### ISSUE THREAD

**Issue by Ghostsl84** [custom-components/hacs#484]
Excuse me my english is not the best :-)

i have a problem white the integration over HACS- Alexa Media Player 2.0.0

i have my configuration.yaml modifyied with this

Alexa
alexa_media:
  accounts:
      - email: xxxxxxxatxxxxx.de
         password: XXXXXXX
         url: amazon.com

and capache maked

and i change the URL in:

url: amazon.de and i have confirme 
and restart.

my Alexa devices habe the state No state available for media_player.alexa

installed over HACS - Home Assistant version 0.97.2

edit: and i have a problem with this
setup of alexa_media is taking over 10 seconds.

Thanks
Ghosty

**Comment by ludeeus** [comment]
HACS have nothing to do with the things you download with it.
You need to open an issue with that specific integration.

**Comment by Ghostsl84** [comment]
Thanks, I'll do it
