### ISSUE TITLE
'type: module'  Missing from configuration suggestion

### ISSUE THREAD

**Issue by gregcsw** [custom-components/hacs#49]
## Version of HACS
0.4.3

## Describe the bug
For 
- group-card
- monster-card
- beer-card
- light-entity-row
- bignumber-card
- entity-attributes-card
- gauge-card
- home-setter
- plan-coordinates

The configuration suggestion is missing 'type: module/js' resulting in the card not working.

Shows:
```
When you add this to your configuration use this: 
  - url: /community_plugin/monster-card/monster-card.js
```

Should be:
```
When you add this to your configuration use this: 
  - url: /community_plugin/monster-card/monster-card.js
    type: module
```

**Comment by ludeeus** [comment]
hacs does not know this, where it show is where the dev has added it to the readme of that repo, hacs looks in that file for a clue, if it can't find it it will not suggest anything, since there is a 50% chance of it being wrong. Untill the dev updates the readme of those repos it will not show.
