### ISSUE TITLE
HACS community  missing from side bar

### ISSUE THREAD

**Issue by Midnight2250** [custom-components/hacs#490]
Am running hassio  .97.2
I installed hacs a while back with no issues. a few days ago I decided to update hacs to the latest version.  After the update, the community tab and icon are now missing from the side bar. I have no access to anything. I know that its working because I have a custom:button-card running properly.
I have tried to reloaded the hacs version 13.2 folder and content  in the  custom_components folder and rebooted home assistant but can't get tab back into the side bar.
```

**Comment by jaxc0402** [comment]
I have the same on .98b2

**Comment by jaxc0402** [comment]
Only thing in the log I see is : 08-28 11:07:27 CRITICAL (MainThread) [hacs.data] [Expecting value: line 1 column 1 (char 0)] Restore Failed!

**Comment by ludeeus** [comment]
See #476
