### ISSUE TITLE
Home Assistant version none

### ISSUE THREAD

**Issue by mcinnes01** [custom-components/hacs#493]
I've installed the latest version of hacs 0.13.2 with the latest version of hassio 0.98.0 as of today. When I try to install anything I get the following message:

Unsupported Home Assistant version
You have version '0.98.0' of Home Assistant, but version 'v2.0.0' of 'Alexa Media Player' require version 'None' of Home Assistant, installation and upgrades are disabled for this integration untill you upgrade Home Assistant.

**Comment by alandtse** [comment]
As a note, this was [previously reported](https://github.com/keatontaylor/alexa_media_player/issues/297#issuecomment-524958573) to us in alexa_media. My understanding is that the `homeassistant` key for min version is optional. We plan to add a min version in our next release this may hit other integrations.

**Comment by mcinnes01** [comment]
I tried a few components and got this, including the spotify playlist. Just come back to it today after not getting anything to install and I get the following: 'HacsManifest' object is not subscriptable.

I also noticed yesterday on the overview page I could see the HACs component itself, when I clicked in to it there was an error also. I can't get to it at the moment as both the store and overview pages have the same error displaying: 'HacsManifest' object is not subscriptable

**Comment by alandtse** [comment]
@mcinnes01 I think you should leave this open for @ludeeus to review. I'm pretty sure there's some error checking that needs to be added and it'll probably be obvious once its reviewed.

**Comment by mcinnes01** [comment]
leaving open for review

**Comment by ludeeus** [comment]
`HacsManifest` does not exist in the current released version (0.13.2), if you see this you did not download it correctly and are running the `master` branch, you should never run the master branch of HACS, it will contain bugs!

This is the reason you get the "require version 'None' of Home Assistant," message.
