### ISSUE TITLE
Setup of hacs is taking over 10 seconds

### ISSUE THREAD

**Issue by Ghostsl84** [custom-components/hacs#497]
Hello

Unfortunately, I have a problem.
Home Assistant always gives me these two errors:

Setup of hacs is taking over 10 seconds
and
Setup of default_config is taking over 10 seconds.

Home Assistant Version: version 0.98.1

I also searched the internet but did not find a solution.
Can someone help me?

Many thanks
Ghostsl

**Comment by Ghostsl84** [comment]
which informations are missing?
Otherwise nothing is written

**Comment by ludeeus** [comment]
1: Version
2: Configuration
3: DEBUG logs

**Comment by Fedemax21** [comment]
Hi, I have the same problem, after adding the lines hacs: and the token, I rebooted and couldn´t connect to the GUI. 
My version is 0.13.2 and my log says: 2019-09-05 20:23:16 ERROR (MainThread) [homeassistant.setup] Setup failed for hacs: Integration not found.
