### ISSUE TITLE
Ui not working

### ISSUE THREAD

**Issue by Fedemax21** [custom-components/hacs#502]
Hi, I´m new to this but I´ve been having a meltdown respecting this. 
I had hassio 2.12 running on my raspberry pi 3 B, and wanted to install hacs 0.13.2. Followed the wiki until adding the token in the configuration.yaml. After that the UI of hassio would not wok anymore despite beeing able to connect through the network folder (using previously instaled samba). I also could connect through the configurator.
This is what the log says: 2019-09-05 20:23:16 ERROR (MainThread) [homeassistant.setup] Setup failed for hacs: Integration not found.
I tried deleting the lines in the yaml and deleting the custom_components folder but I can not open the https://XXX.duckdns.org:8123
My YAML: 
default_config:
api:
alexa:
  smart_home:
http:
    ssl_certificate: /ssl/fullchain.pem
    ssl_key: /ssl/privkey.pem 
    base_url: https://XXX.duckdns.org:8123
# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

If someone can help I would be glad

**Comment by ludeeus** [comment]
Then you have bigger problems then just this component, try it again when you get it sorted out.
