### ISSUE TITLE
Feature Request: Ignore README.md updates

### ISSUE THREAD

**Issue by noxhirsch** [custom-components/hacs#515]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I get an update notification and the only thing updated is README.md

**Describe the solution you'd like**
I don't know if it's even possible, but it would be great if HACS could ignore commits which only address README.md

**Comment by ludeeus** [comment]
That would not be possible from HACS, it is however possible for the developer to start using GitHub releases in his/hers repositories, if he/she does, you will only get updates when a new release is published.
