### ISSUE TITLE
Can't found any card when installed by hacs

### ISSUE THREAD

**Issue by Aygotori** [custom-components/hacs#524]
Hi there,

I can't get any plugin to work when installed by hacs...
The plugins are installed correctly, i can see them in the folder `www/community/`  but i can't found any card in UI...  

I already try to make manual cards to call plugins but didn't work...

A little help will be appreciated! =)

Im running hassio 0.98.5 on Rpi4

**Comment by ludeeus** [comment]
Since you see the files HACS has done its job.
For support about how to use custom stuff in Lovelace try asking on Discord or the forum.
