### ISSUE TITLE
Support for On-demand (manual) update checking (disabling automatic checks)

### ISSUE THREAD

**Issue by arigit** [custom-components/hacs#53]
**Is your feature request related to a problem? Please describe.**
Currently HACS is constantly checking for updates, every 30min/500min etc depending on the case (see the below extract of HACS documentation)

**Describe the solution you'd like**

In my use case, I only run very stable components and have no need of automated checks every 30 minutes. At this point I update HA every quarter or so and custom components only occassionally, say weekly or monthly. I.e. there is no point on keeping my RPi busy checking stuff for no reason.

This is a feature request to add either a GUI or configuration file (yaml) support for disabling HACS periodic 30m/500m checks and only check when manually triggered 

**Describe alternatives you've considered**

perhaps add a "pause" and "play" button.

**Additional context**
N/A

-------------------------------------------

Installed elements

HACS will check for updates to installed elements:

    At startup.
    Every 30 minutes after HA startup.

Everything else

HACS will check for updates to every element:

    At startup
    Every 500 minutes after HA startup.

Manually trigger updates

You can also force a check by clicking the “RELOAD DATA” button under the “SETTINGS” tab (This will force a reload of everything.)

Under the “SETTINGS” tab there is also a reload icon to the left of every custom repository you have added, clicking that will reload info for it.

On each ElementView (the page with details about the element) there is a reload icon at the top-right corner, clicking that will reload it.

**Comment by ludeeus** [comment]
This feels weird, updates are the main reason this exists, I can't imagine most users would want this and will consider this an edge case I will not add in.

As a workaround for your specific needs, you can just remove these lines:
https://github.com/custom-components/hacs/blob/65d072724ea1d785436b36fba43ce7ff0ee315c3/custom_components/hacs/hacsbase.py#L44-L48

**Comment by emics** [comment]
The function for disable automatic update or better define custon interval is important for people like me.
I use 4G broadband connection and HACS keep a lot of tarffic of my 50GB sim card.
for my personal use is better set custom interval update.

thanks for patience
