### ISSUE TITLE
install all custom components to none dir

### ISSUE THREAD

**Issue by Stephan296** [custom-components/hacs#530]
When you install a custom_component the new dir is standard: 

When installed, this will be located in '/config/custom_components/**None**', you still need to add it to your 'configuration.yaml' file.

**Comment by ludeeus** [comment]
[How to submit issues](https://beta--hacs.netlify.com/issues/)

**Comment by DavidFW1960** [comment]
I think I see this when I updated the Authenticated sensor recently... I created an issue there
