### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by mclaudiopt** [custom-components/hacs#54]
Hello
congratulations for the great app !

i have added the logger: altough it generates huge log... is there anyway to reduce all logs only to warn level for example ?
i tried in several ways but cannot eliminate all the info and debug informations on the log
thank you

**Comment by ludeeus** [comment]
No this is not possible, and will not be possible for a few versions.
The reason: it's still new, I expect there to be issued, I need that log to troubleshoot.
Forcing debug will be removed in a future release.
