### ISSUE TITLE
Duplicate integration names

### ISSUE THREAD

**Issue by maximunited** [custom-components/hacs#540]
**Is your feature request related to a problem? Please describe.**
I have 2 integrations with the same name: Google Keep
1. [PiotrMachowski/Home-Assistant-custom-components-Google-Keep](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Google-Keep)
2. [aFrankLion/hass-google_keep](https://github.com/aFrankLion/hass-google_keep)
Both save their files in custom_components/google_keep

**Describe the solution you'd like**
I would like to use both. Perhaps allow an override or a custom dir name in case there a name duplication

**Comment by ludeeus** [comment]
That will not work, the configvalidation require the dirname to be the same as your config entries and the DOMAIN key in the configuration.

In a perfect world, those two developers would colaborate on 1 integration, but that is not up to HACS (me) to dictate.
