### ISSUE TITLE
Integration hacs not found

### ISSUE THREAD

**Issue by macguru341** [custom-components/hacs#541]
## Describe the bug
can't had it to config file.

## Debug log

```text

Add your logs here.

```

**Comment by macguru341** [comment]
hello
i'm trying to had this to my config and get an error when i want to restart hassio :

Log Details (ERROR)
Tue Sep 17 2019 20:20:07 GMT+0300 (Israel Daylight Time)
Component error: hacs - Integration hacs not found.

this is my configuration.yaml 

# Example configuration.yaml entry
default_config:

hacs:
    token: ddf0aea246c7a0860e0a10698f57299fXXXXXXX
    sidepanel_title: true
    sidepanel_icon: true
    theme: true

what am i doing wrong?

**Comment by ludeeus** [comment]
Paaste a screenshot of the folder

**Comment by ludeeus** [comment]
@macguru341 ?
