### ISSUE TITLE
Add ability for developers to pin available versions

### ISSUE THREAD

**Issue by alandtse** [custom-components/hacs#545]
**Is your feature request related to a problem? Please describe.**
We may release breaking versions of an integration and people complain they like the old version. ;)

**Describe the solution you'd like**
Allow integrations to pin versions somehow. Perhaps automatically grab the latest major version? i.e., if we're working on the v2.x branch always show the latest v.1.x branch. I know your components don't prepend `v` to releases, but I'd like to make sure `v` is supported for my use case. 

**Describe alternatives you've considered**
Currently relying on "pre-release" flag to manually remove older versions so the last major version doesn't scroll off the end.

**Additional context**
Yes, working on not having a reason for people to downgrade.

**Comment by ludeeus** [comment]
How about you just don't release broken stuff? 🤣

Currently I actually grab all releases, but only show the last 5 (better UX), but I guess I can remove that filer 🤷
Adding a list of pinned versions adds complexity and confusion to the developer and the user.

**Comment by alandtse** [comment]
Maybe expose a global setting so people can expand the filter beyond 5 and master. I think the filter makes sense as a default setting.

**Comment by ludeeus** [comment]
Next version adds the concept of options (both UI and YAML) 
Would be a great place for it, you got a suggestion for (All)?
I guess setting a high # would do 🤷

**Comment by ludeeus** [comment]
![image](https://user-images.githubusercontent.com/15093472/65370373-46870f80-dc58-11e9-8d4f-e9ac71ae667b.png)

Added with b04aa34

**Comment by alandtse** [comment]
Thanks!

**Comment by ludeeus** [comment]
0.14.0 is now released.
