### ISSUE TITLE
How do I uninstall HACS?

### ISSUE THREAD

**Issue by rgogada** [custom-components/hacs#546]
## Describe the bug

tried below
1) removed the custom component 
2)removed the config entry
3) restarted but the log still says "Setup failed for hacs: Integration not found."

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
Have no idea, never tried, will look into it

**Comment by platini76** [comment]
which repository I have to add to my hass.io installation to install hacs directly?

**Comment by ludeeus** [comment]
1: Remove from `configuration.yaml`
2: Restart HA
3: Restart HA
4: Delete `custom_components/hacs`

**Comment by peterpme** [comment]
Hi there, I've been searching everywhere inside my config for `hacs` with no luck. What exactly are we looking for?
