### ISSUE TITLE
HACS disappeared from the sidebar

### ISSUE THREAD

**Issue by robertsorensen** [custom-components/hacs#556]
## Version of HACS
I believe I'm on the latest (14.2) but I'm not sure

I was running version 13.2 but saw that a newer version (13.3) was available.
I did select update and eventually restarted HA. After this HACS had disappeared from the sidebar and I'm not sure how or if I can launch it.
I did notice that it appears on the integration page but still I don't see how I can launch it.

## Debug log

From my log all I see related to HACS is this:
2019-09-21 13:45:30 CRITICAL (MainThread) [hacs.data] [Expecting value: line 1 column 1 (char 0)] Restore Failed!

Add your logs here.

```

**Comment by ludeeus** [comment]
"Restore Failed!"
one (or more) of the hacs files under .storage is corrupted

**Comment by cafeywifi** [comment]
@ludeeus I seem to be having the same issue... what's the process to reset the storage files? I just deleted and copied the hacs subdirectory from the last version from GitHub. Thanks

**Comment by Decman84** [comment]
Hi, Im having a similar issue. I've tried updating merging the latest files from GitHub over the top with no success.
Where is the location of the storage folder, i've scanned the folders but cannot spot it?

**Comment by pennycham** [comment]
same issue here. also trying to find that .storage folder

**Comment by ludeeus** [comment]
It's in your configuration directory

**Comment by Macke87** [comment]
hi, im having the same problem. the hacs disappeared from the sidebar. i deleted the hacs files in .store but stil not working. :/

**Comment by ludeeus** [comment]
@Macke87 you **only** need to do that if you have that exact error message, and it works, if you have issues open a separate issue or search the closed one for the error you are seeing.
