### ISSUE TITLE
Not restarting after HACS install

### ISSUE THREAD

**Issue by RolandGoud** [custom-components/hacs#566]
When installing HACS 0.14.1 after the initial reboot and adding the github token. HA will refuse to restart without giving any info in the log. 

Just looks like the restart is not triggered at all.

**Comment by ludeeus** [comment]
Check your config (not in the UI)

**Comment by RolandGoud** [comment]
Not specific enough.... I just di a fresh install added ahcs and same issue... only with 0.13.2.

there is no log file in my config folder

**Comment by RolandGoud** [comment]
I copied only the hacs folder this time (into cusotom_components folder I added myself) and it is working now.....Before I was copying the whole custom_components folder....could that have been the problem?
