### ISSUE TITLE
Allow sidebar entry to be grouped on bottom with other system functions

### ISSUE THREAD

**Issue by KaiboshOz** [custom-components/hacs#567]
Purely a cosmetic change, but an option to include the HACS link in the sidebar on the bottom (with Config; Dev Tools; Hass.io icons) rather than the default at the top (with Overview; Logbook; etc.) would be nice..
It seems (to me at least) like a better fit with the lower section of the sidebar after it was split into top and bottom.

Perhaps an additional configuration option similar to ''sidepanel_title'', but true/false like ''sidepanel_top"

Edit: Assuming of course that entries can be added to the bottom of the sidebar within HA and non core-HA stuff can only be added to the top..

**Comment by ludeeus** [comment]
They can, but that would be a hack and will be subject to breaking since I would need to change the HA frontend during runtime.
Unless HA makes that possible with the panel registration I will not add this.
