### ISSUE TITLE
Custom github version tracking

### ISSUE THREAD

**Issue by starkillerOG** [custom-components/hacs#569]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to google all github repositories to check if there are new updates available for all the projects I use in my smart home and often find out there is nothing to update or the opposite happened and I am multiple versions behind with tons of new nice features and stability improvements.

That is also why I love HACS so much, it gives me a really nice overview of all my custom components where I can see in one glance if there are updates. (and of course it offers a very easy way to perform the upgrade).

However other related smart home software such as esp8266_milight_hub and OpenMQTTGateway and others that I use are not available in that really nice HACS overview.
Moreover the current HomeAssistant version (and if an update is available) is also not in that overview

**Describe the solution you'd like**
I would love it if you could add a custom github project to HACS that would then just track the current released (stable) version of that project and show up in the HACS overview as being green if you are on the current (stable) version. As soon as that github project would release a new version it would turn red in the HACS overview. Of course you cannot update such projects from within HACS and are not able to track which version is being used, so I purpose there would be a simple button that you can click in order to indicate that you have updated to the new version making the custom github project green again in the HACS overview.

Therefore this would not include the update process itself or the checking of the current installed version. It would just be a tracker if new versions are released in one nice overview.

**Describe alternatives you've considered**
For HomeAssistant version I could use the “Version Sensor” platform (https://www.home-assistant.io/components/version/) build into HomeAssistant, however it will not show up in the HACS overview but in some other tab in the front-panel. I would really like to have one overview for all my version checking.

For custom github responsories like esp8266_milight_hub and OpenMQTTGateway, I could probably make a similar sensor work in the frontend using something like the “RESTful Sensor” (https://www.home-assistant.io/components/rest/), or write my own python script and then just use an “Command line Sensor” (https://www.home-assistant.io/components/sensor.command_line/) to get the value of the python script in the front-end of HomeAssistant. But again then it would not be included in the nice overview of HACS.

**Additional context**

**Comment by ludeeus** [comment]
HACS is a downloader, and this will be way out of the scope of what I intended for it.

I think what you want is this one https://www.home-assistant.io/components/github/

BTW: Awesome FR, it's not often I see them that detailed 🎉

**Comment by starkillerOG** [comment]
@ludeeus Thanks for the quick replay and the useful link!
That is indeed an easy way to get the sensor in the frontend, thanks.

Would still love to have it all in one place in the HACS overview.
But will settle for the frontend then...
