### ISSUE TITLE
UI Translations

### ISSUE THREAD

**Issue by ludeeus** [custom-components/hacs#585]
Hello there 👋 

The new experimental UI for HACS that was added in [Ring Of Fire (0.15.0)](https://github.com/custom-components/hacs/releases/tag/0.15.0) have support for translation of the UI.

Wouldn't it be awesome to have HACS show in _your_ native language? :D 

Update:
For information about this, check out this link https://hacs.netlify.com/#translations

**Comment by ludeeus** [comment]
Pinging previous translators and @hwikene 
@xMrVizzy @bieniu @royto @jalbertseg @pepeEL @TychoWerner

**Comment by thallesbrandao** [comment]
I'll take this PT-BR

**Comment by pepeEL** [comment]
How i can set PL language ?
What you mean as you write: The PL are only for config_flow (when you initially configure it in the UI) ?

**Comment by xMrVizzy** [comment]
#598

**Comment by ludeeus** [comment]
@pepeEL it is currently **only** for this part.
![image](https://user-images.githubusercontent.com/15093472/66024666-bcab3200-e4f4-11e9-9394-eabf1acc8d20.png)

**Comment by Andy9822** [comment]
I see the Spanish translation it's not finished. I can complete it!

**Comment by ascillato** [comment]
@Andy9822 Ups, I was already working on that file. Just submitted. Please check it if it needs any improvements. Thanks.

**Comment by ludeeus** [comment]
Awesome work to everyone that have contributed translations, I have realized that managing this with PR's are not great...

I'm looking into using https://lokalise.com for this instead, so if you plan on creating a PR with a language, please hold on a few hours :)

**Comment by ludeeus** [comment]
HACS is now on Lokalise :tada: https://hacs.netlify.com/#translations

**Comment by bieniu** [comment]
@ludeeus There is no Polish on Lokalise.

![image](https://user-images.githubusercontent.com/478555/66072643-b7ca9a80-e555-11e9-8d43-28eecdcbdbbd.png)

**Comment by ludeeus** [comment]
That is correct @bieniu I need to resolve #603 before I can upload the initial file

**Comment by royto** [comment]
French translation updated

**Comment by ludeeus** [comment]
@bieniu It has moved now

**Comment by sirotkaslo** [comment]
Can you add slovenie also? thanks

**Comment by NickolaosC** [comment]
French Translation updated as well, a provided alternative translation for a few of the entries.
