### ISSUE TITLE
Problem with translation PL

### ISSUE THREAD

**Issue by pepeEL** [custom-components/hacs#596]
## Version of HACS
0.15

## Debug log

```text

Add your logs here.

```

Hi
I use HACS and support polish translation but i still dont have polish language in HACS.... On Home Assistant i use polish lang.

**Comment by ludeeus** [comment]
The PL are only for config_flow (when you initially configure it in the UI)

**Comment by pepeEL** [comment]
I dont understand....how set PL in HACS?
