### ISSUE TITLE
Cards of experimental view don't open in Firefox

### ISSUE THREAD

**Issue by VDRainer** [custom-components/hacs#612]
## Version of HACS
0.15.0 experimantal view

## Describe the bug
Clicking on a card of the experimental view in Firefox does nothing, Chrome works.

## Debug log

```text
TypeError: t.path is undefined3 main.js:177:142
    ShowRepository http://192.168.77.67:8123/hacs_experimental/main.js:177
    handleEvent http://192.168.77.67:8123/hacs_experimental/main.js:1
    __boundHandleEvent http://192.168.77.67:8123/hacs_experimental/main.js:1
```

**Comment by ludeeus** [comment]
It looks like it's more than just the cards :/

**Comment by ludeeus** [comment]
<https://github.com/custom-components/hacs/commit/de4cdc9988849445c6afa9e877886371bd36879d>
Will release a new version with a fix for this and translations when Lokalise are back up https://lokalise.statuspage.io/

**Comment by ludeeus** [comment]
<https://github.com/custom-components/hacs/releases/tag/0.15.1>
