### ISSUE TITLE
Can't see new experimental interface in Chrome

### ISSUE THREAD

**Issue by atomicpapa** [custom-components/hacs#616]
## Version of HACS

Version 0.15.0

## Describe the bug
New experimental interface does not show up after installing new version, checking the checkbox in Integrations, rebooting, deleting cache, ctrl-f5 reloading of page

## Debug log

Nothing shows up in logs related to HACS

**Comment by ludeeus** [comment]
Did you configure hacs using the UI or YAML?

**Comment by daneberryman** [comment]
my HACS is gone, all the custom integrations still working. but no sign of HACS anywhere

**Comment by ludeeus** [comment]
That is not relevant to the issue

**Comment by ludeeus** [comment]
@atomicpapa ?

**Comment by colemamd** [comment]
I have the same issue using Chrome, and am using YAML

**Comment by ludeeus** [comment]
If you use yaml you need to add it to the yaml config, not the UI options.
