### ISSUE TITLE
Unable to install Mini Graph Card

### ISSUE THREAD

**Issue by lollo78** [custom-components/hacs#618]
Hi, thanks a lot for HACS. It looks so cool!!!
I can't install "Mini Graph Card". Page refresh with an orange row but plugin is not download/installed.
No issue with other plugin.
Hope you can fix it. Thanks a lot
Best regards

**Comment by ludeeus** [comment]
I can not

**Comment by lollo78** [comment]
It's an HACS issue or we need to ask a fix to kalkih?

**Comment by ludeeus** [comment]
I have no idea, without debug logs I can not do anything

**Comment by lollo78** [comment]
After a reboot, the plugin is installed.
