### ISSUE TITLE
Component not found: hacs

### ISSUE THREAD

**Issue by johntdyer** [custom-components/hacs#62]
## Version of HACS
0.5.1

## Version of Hassio
0.94.0

## Describe the bug
I moved hacs: into the configuration.yaml as suggested in #48 and now when I run my pre-restart validation I get the following error:

```
~# hass --script check_config -c  /usr/share/hassio/homeassistant/ -i debug
Testing configuration at /usr/share/hassio/homeassistant/
Failed config
  General Errors:
    - Component not found: hacs

Successful config (partial)
  debug:
```

Whats strange ( good? ) is that this does not seem to be a real error since by all means it appears to be working just fine... I do rely on this sanity check before restarting and I'd love to remove this noise if possible

Thanks

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
This is out of the scope of this component and I will not investigate this.

**Comment by johntdyer** [comment]
@ludeeus  How is this out of scope for this component ? I add 

```yaml
hacs:
  token: !secret my_github_access_token
```

to my configuration.yaml and i get this warning.  If I remove it I dont...

**Comment by ludeeus** [comment]
The reason is per your own word "not seem to be a real error" (gives a false negative) and that check is not provided by this component.

**Comment by wired-dev** [comment]
I would counter that if the script is giving wrong info it is an error.

**Comment by KevinCostner1** [comment]
@johntdyer hey man.. same issue here. Did you solve it?

**Comment by johntdyer** [comment]
@KevinCostner1  - nah never did solve it...
