### ISSUE TITLE
Adding Italian to lokalise 

### ISSUE THREAD

**Issue by bennydente** [custom-components/hacs#626]
As object. Please add Italian to lokalise. Thanks.

**Comment by ludeeus** [comment]
Which one?
![image](https://user-images.githubusercontent.com/15093472/66258618-b98b9c80-e7a7-11e9-9bae-b6867ca72523.png)

**Comment by ludeeus** [comment]
Looks like it's `it` that HA uses, so:

![image](https://user-images.githubusercontent.com/15093472/66258641-feafce80-e7a7-11e9-8a65-31008a67e486.png)
