### ISSUE TITLE
Danobot repository hangs up my Home Assistant

### ISSUE THREAD

**Issue by rschuiling** [custom-components/hacs#627]
## Version of HACS
Latest (can't check right now since HA won't start)

## Describe the bug
Home Assistant suddenly crashed, and restarting the Docker doesn't help to gain access. I should mention I do not have the Danobot integration installed.

## Debug log
```text
2019-10-05 19:36:50 ERROR (MainThread) [hacs.repository.integration.danobot.entity-controller] Missing manifest file.
2019-10-05 19:36:50 ERROR (MainThread) [hacs] Validation for danobot/entity-controller failed.
```

**Comment by ludeeus** [comment]
Unless you have an old version of HACS/HA it should not hang

**Comment by rschuiling** [comment]
Never mind, something else seems to be the matter. After rebooting again, the Danobot error is gone. HA is running but it refuses to load the UI :-(
