### ISSUE TITLE
Package hacs setup failed. Component hacs unable to import

### ISSUE THREAD

**Issue by atomicpapa** [custom-components/hacs#63]
Receiving following error when checking configuration in Configuration / General:

```
Configuration invalid
Package hacs setup failed. Component hacs unable to import
```

 Running HACS 0.5.1 and have updated immediately prior to posting this to include files that were updated 2 days ago.

configuration as follows:

```
hacs:
  token: !secret hacs_github_token
```
"Community" does not appear in menu on left side.  No errors showing up in log.

Everything working properly until upgrade to Hassio 0.94.1

**Comment by ludeeus** [comment]
For a reason unknown to me it can not be placed in a package, you need to have it directly in configuration.yaml

I will not investigate why this is happening, since when it's in configuration.yaml everything is fine.

**Comment by glassbase** [comment]
Same for me. Tried to put config in packages/ and was not working. Had to put in configuration.yaml
