### ISSUE TITLE
Repository with both integration and plugin component

### ISSUE THREAD

**Issue by r-renato** [custom-components/hacs#632]
Hi, I have a github repository that contain both integration and plugin component, so I registered the repository both in integration and plugin data store.

In the store, when I ask to install the component, hacs installs either  the integration or the plugin.

Is possible make sure that hacs installs both?

Thanks,
Renato

**Comment by ludeeus** [comment]
No that is not possible, the repository can only cantain one element, as stated in the developer documentation.
