### ISSUE TITLE
Experimental build doesn't allow saving manually added repo

### ISSUE THREAD

**Issue by cogneato** [custom-components/hacs#638]
## Version of HACS
Version: 0.15.2 (Experimental)

## Describe the bug
The save icon for manually adding a repository on the settings page is broken.

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
You should see logs, either in the browser console or with debug enabled for HACS, what does it say?

**Comment by ludeeus** [comment]
@cogneato ?

**Comment by ludeeus** [comment]
<https://discordapp.com/channels/330944238910963714/609399695466430465/636213882611826718>
