### ISSUE TITLE
Validation for custom-components/hacs failed with GitHub returned 401 for https://api.github.com/rate_limit

### ISSUE THREAD

**Issue by ln-12** [custom-components/hacs#642]
#### Problem
After a fresh install of Home Assistant on a Raspberry Pi I wanted to try out HACS. I strictly followed the instructions [here](https://hacs.netlify.com/installation/manual/) and [here](https://hacs.netlify.com/installation/configuration/) but as you can see on the attached screenshot something is going wrong. Am I missing a configuration step or might there be an issue on the side of HACS?

#### Home Assistant
System: HassOS 2.12
Deployment: production
Version: 189

#### HACS 
Version: 0.15.2

#### Debug Log
<img width="799" alt="Bildschirmfoto 2019-10-09 um 10 39 35" src="https://user-images.githubusercontent.com/36760115/66465452-28efdd80-ea81-11e9-84f9-efbae840d4ec.png">

**Comment by ludeeus** [comment]
Your token is not valid, try generating a new one.

**Comment by ln-12** [comment]
I don't know why, but after generating a new one everything is working properly now. Thanks a lot for the quick reply! :)
