### ISSUE TITLE
0.15.4. missing version bump

### ISSUE THREAD

**Issue by tribut** [custom-components/hacs#650]
## Version of HACS

0.15.4

## Describe the bug

The version in `const.py` was not updated (it is still 0.15.3), so hacs will always show as "upgrade available".

**Comment by ludeeus** [comment]
You know it took you longer to create this issue then a PR to change it? 😅

**Comment by tribut** [comment]
Heh. Wasn't sure if there was some magic involved in releasing HACS and whether 0.15.4 or 0.15.5 was correct. Also didn't have much time, because dinner was waiting ^_^ But sure, here is a PR.
I assume 0.15.4 already points to the old commit, so I incremented to 0.15.5.

**Comment by ludeeus** [comment]
oh.. :/
I have already pushed 0.15.5 <https://github.com/custom-components/hacs/releases/tag/0.15.5>
