### ISSUE TITLE
HACS throwing error in Travis CI

### ISSUE THREAD

**Issue by atomicpapa** [custom-components/hacs#654]
## Version of HACS

0.15.5

## Describe the bug
Travis CI throws error for hacs options. Component works properly and passes Config Checker.  This is preventing Travis from otherwise completing a check of my config.
``` 
 hacs: 
    - Invalid config for [hacs]: [options] is an invalid option for [hacs]. Check: hacs->hacs->options. (See ?, line ?). Please check the docs at https://home-assistant.io/integrations/hacs/
```
## Config

```text

hacs:
  token: !secret hacs
  appdaemon: true
  python_script: true
  theme: true
  options:
    experimental: true

```

**Comment by ludeeus** [comment]
I'm not going to configure Travis to test this.
That error indicates that your pipeline is using an old version of the integration or that Travis is doing something weird that it shouldn't.

I run that test with every push to master using a GitHub Action to test 3 different versions of HA on 2 different versions of Python:
Action: <https://github.com/custom-components/hacs/blob/195ec2525e4dafe84a5412af6c9494c1886bc6a7/.github/workflows/testing.yml#L12-L68>
Result: <https://github.com/custom-components/hacs/runs/255577531#step:7:9>

You have 4 options:
- Disable HACS an/or custom_components in your run.
- Migrate your CI to GitHub Actions.
- Use config_flow for your config (no YAML).
- Remove the options from your configuration.

**Comment by atomicpapa** [comment]
not familiar with Github Actions, so I guess it's time to do a little research
