### ISSUE TITLE
Sensor to show new repos are available

### ISSUE THREAD

**Issue by holdestmade** [custom-components/hacs#661]
**Is your feature request related to a problem? Please describe.**
Liking the new(ish) New Repos section, would be good if we could have a sensor showing when new ones are available (and possibly how many) to add to the gui

**Describe the solution you'd like**
A sensor showing when new ones are available (and possibly how many) to add to the gui

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by ludeeus** [comment]
I personally would find that sensor annoying to have in my setup.
Why do you want this?

Is this for automation or display only?
If it's for automation, you can use events.

**Comment by ludeeus** [comment]
I think this is enough <https://hacs.netlify.com/docs/basic/events#automation-example>.

That should give you an idea of what you can do.
And that example _should_ be able to work with <https://github.com/gadgetchnnel/lovelace-home-feed-card> if you wanted it in the frontend as well.
