### ISSUE TITLE
Add a restart button

### ISSUE THREAD

**Issue by hakana** [custom-components/hacs#67]
When HACS show the message "You need to restart Home Assisant to start using the latest version of HACS." it would be nice with a button/link there for restaring.

**Comment by ludeeus** [comment]
If there at some point there is a breaking change in HACS, that would be bad.
No matter how many warnings are added to the release notes, there will always be someone that will just hit that restart button.

By not offering that inside HACS, the user will _hopefully_ think twice before doing it.

I think HA itself has enough options to restart, and I will not add this in.
