### ISSUE TITLE
"The frontend of HACS have been disabled until you restart Home Assistant."

### ISSUE THREAD

**Issue by Stooovie** [custom-components/hacs#672]
Whenever I try to access HACS, I get a banner warning "The frontend of HACS have been disabled until you restart Home Assistant.". Restart of HA or even physical reboot of Pi4 doesn't help. Removing the component and entry from config yaml allows me to reinstall HACS but the issue always comes back. Hassio 100.1 (happened with 99.6 too) on RPi4 32bit.

Logs give:
- Setup of hacs is taking over 10 seconds.
- [Expecting value: line 1 column 1 (char 0)] Restore Failed!
- Removing unknown panel hacs

Any tips? 

EDIT: I have been using HACS succesfully, so it's probably not a faulty installation.

**Comment by ludeeus** [comment]
See the pinned issue

**Comment by johncolet** [comment]
See this.
https://github.com/hacs/integration/issues/1864#issuecomment-865450376
