### ISSUE TITLE
Integration and configuration missing content

### ISSUE THREAD

**Issue by pho3nixf1re** [custom-components/hacs#678]
## Version of HACS

0.15.7

## Describe the bug

During the first time installation and setup of HACS when adding the integration there is no content in the integration list for HACS. The configuration screen is also missing content. See screenshots. The HACS UI displays fine and the component functions correctly.

![Screen Shot 2019-10-13 at 13 58 15](https://user-images.githubusercontent.com/96882/66721637-5a8ede80-edca-11e9-8cde-c3d4fa32c921.PNG)
![Screen Shot 2019-10-13 at 13 58 25](https://user-images.githubusercontent.com/96882/66721638-5a8ede80-edca-11e9-9275-52de5df97bcc.PNG)
![Screen Shot 2019-10-13 at 14 04 51](https://user-images.githubusercontent.com/96882/66721641-64b0dd00-edca-11e9-98cc-825c3748924a.PNG)

## Debug log

```text
2019-10-13 14:58:50 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-10-13 14:59:12 ERROR (MainThread) [hacs.repository.integration.Michsior14.ha-laser-egg] Repository is archived.
2019-10-13 14:59:13 ERROR (MainThread) [hacs] Validation for Michsior14/ha-laser-egg failed.
2019-10-13 14:59:13 ERROR (MainThread) [hacs.repository.integration.Michsior14.ha-kaiterra] Repository is archived.
2019-10-13 14:59:13 ERROR (MainThread) [hacs] Validation for Michsior14/ha-kaiterra failed.
```

**Comment by ludeeus** [comment]
Looks like you are missing the .translations folder, if you use samba and windows that folder is hidden

**Comment by pho3nixf1re** [comment]
Ah! but I use macos with hidden files enabled. However I used Transmit sftp to move the files. I bet than is where the error occurred. I'll take a look this morning and close this with more details.

**Comment by hacslarshome** [comment]
I have the same issue. .translation is present. Could the problem lie in the language used by my HA? It's danish.

**Comment by hacslarshome** [comment]
Negative. Still same problem.

`
Config entry for hacs not ready yet. Retrying in 80 seconds.
6:09 PM config_entries.py (WARNING) - message first occured at 6:03 PM and shows up 5 times
Error unloading entry for sensor
6:09 PM helpers/entity_component.py (ERROR) - message first occured at 6:02 PM and shows up 9 times
[Expecting value: line 1 column 1 (char 0)] Restore Failed! see https://github.com/custom-components/hacs/issues/639 for more details.
6:09 PM custom_components/hacs/hacsbase/data.py (CRITICAL) - message first occured at 6:02 PM and shows up 9 times
Config entry for hacs not ready yet. Retrying in 40 seconds.
6:03 PM config_entries.py (WARNING)
Config entry for hacs not ready yet. Retrying in 20 seconds.
6:02 PM config_entries.py (WARNING)
Config entry for hacs not ready yet. Retrying in 10 seconds.
6:02 PM config_entries.py (WARNING)
Config entry for hacs not ready yet. Retrying in 5 seconds.
6:02 PM config_entries.py (WARNING)
`

**Comment by hacslarshome** [comment]
Disregard my comment.

The issue was a different one. solved by https://github.com/custom-components/hacs/issues/639

**Comment by pho3nixf1re** [comment]
Yup, that was the issue. My sftp client had hidden files disabled and so the `.translations` folder got ignored initially.

**Comment by folksman** [comment]
i have same errors but .translations folder  is copied. i double checked it in configurator
