### ISSUE TITLE
Move HACS Bot to GitHub Actions

### ISSUE THREAD

**Issue by ludeeus** [custom-components/hacs#679]
All features of [hacs-bot](https://github.com/ludeeus/hacs-bot) should be moved to GitHub actions in this repo.

_Projekt started_ https://github.com/hacs/actions

- [x] Greeter message for new issues
- [x] Greeter message for new pull requests
~~- [ ] Pull request Labeler for the `master` branch~~
~~- [ ] Issue Labeler~~
~~- [ ] Known issues handler~~
- [x] Closed issue handler
- [x] Test repository

**Comment by salem84** [comment]
Hi @ludeeus, can I help you on this task?

**Comment by ludeeus** [comment]
I'm almost done :D 
So that would probably not be needed 
The new stuff lives here https://github.com/hacs/actions

**Comment by ludeeus** [comment]
That did not work at all...

When Github actions run from a fork, it only has read access
<https://github.com/hacs/actions> has been deleted in favor of https://github.com/hacs/bot
