### ISSUE TITLE
plugins only 'Custom element doesn't exist'

### ISSUE THREAD

**Issue by fullKrum** [custom-components/hacs#689]
0.15.7 Version of HACS

## Describe the bug
I have an issue using HACS but only for plugins. Integrations and themes work without a problem. I have searched forums and Reddit but not as yet found a solution. While I do not think it is a HACS issue because as such given that I can access the installed plugin via the HACS interface (open plugin)?
I could do with a couple of pointers. Simply ruling out all the possible options as I do my own process of troubleshooting!
Start with the last thing that changed and work backwards..
Chances are that It is my shovel fingers that have caused my predicament but without more informed guidance I seem unable to isolate the cause of my issue.

If I can rule out HACS then it is something for the forums. One step nearer to resolution!

I thank you for any guidance you can give.
John

## Debug log

```text

Debug after a restart available here.
[home-assistant.log.zip](https://github.com/custom-components/hacs/files/3726634/home-assistant.log.zip)


```

**Comment by ludeeus** [comment]
Since you can see the plugin when you click the open plugin button, you can rule out HACS ;)

**Comment by fullKrum** [comment]
Thought so. Thank you for confirming that.
