### ISSUE TITLE
Look like something is wrong with formating in latest version

### ISSUE THREAD

**Issue by hakana** [custom-components/hacs#69]
# Version of HACS
0.5.1

## Describe the bug
Look like problem with layout/css, see pictures

## Debug log
<img width="868" alt="HACS1" src="https://user-images.githubusercontent.com/1168654/59184386-52016f80-8b6e-11e9-9a1f-7228093d8249.PNG">
<img width="841" alt="HACS2" src="https://user-images.githubusercontent.com/1168654/59184387-52016f80-8b6e-11e9-89d9-58f3b17ff676.PNG">
<img width="857" alt="HACS3" src="https://user-images.githubusercontent.com/1168654/59184389-52016f80-8b6e-11e9-9752-124d1f87568f.PNG">

**Comment by ludeeus** [comment]
Do a hard reload in your browser.

**Comment by ludeeus** [comment]
If you upgraded from a version <0.4.4
It downloaded the hacs.js and hacs.css files to /config/custom_components/ instead of /config/custom_components/frontent/elements/

Just move them to the correct location if this is the case for you.

**Comment by hakana** [comment]
I don't have hacs.js or hacs.css. I added them from repro and now it working.
