### ISSUE TITLE
Support dependencies

### ISSUE THREAD

**Issue by 1DontEx1st** [custom-components/hacs#693]
**Describe the solution you'd like**
Looking at layout-card, it requires card-tools. I'd imagine there might be other cards that have similar dependencies, so it would be nice to either chain the install(s), or at least indicate if something is needed and not present.

**Describe alternatives you've considered**
Just leave it to the user to *gasp* read the docs.

**Comment by ludeeus** [comment]
This can't be done in a clean way.
<https://discordapp.com/channels/330944238910963714/460846676358332417/584464020854014084> indicates that `card-tools` _may_ be deprecated at some point in the future.

There are 3 things stopping this from be possible for me to add in HACS.

1. Dependencies can be "anything" it can be a GitHub repo/npm package/an integration(?)
2. The repository (like card-tools) does not exist in HACS, so HACS can not know how to install it.
3. The user would _still_ need to follow the docs for a now unknown thing that was automatically installed to use it (add it under resources.)
