### ISSUE TITLE
[Question] Why do you need a Github token ?

### ISSUE THREAD

**Issue by bokub** [custom-components/hacs#710]
Hi,

The installation docs are really easy to follow, but I'm wondering why a Github token is needed, and I'm a little bit concerned with giving away tokens not knowing the usage.

I tried to understand, I looked everywhere in the documentation, no answer. I finally decided to uninstall HACS.

Maybe you could give an answer in this issue, and add a few lines of explanation in the documentation ? (I was thinking [here](https://hacs.netlify.com/docs/configuration/start) and [here](https://hacs.netlify.com/docs/configuration/pat))

Thanks

**Comment by ludeeus** [comment]
Short: HACS uses GitHub's API to fetch info about every repository in the "store".
Without an access token, you get 60 calls pr/h
With an access token, you get 5000 calls pr/h

60 calls are not enough for HACS to function.

**Comment by bokub** [comment]
All right ! That's clear now

I'll add the explanation to the docs if you want 👍 

By the way, what are the API routes used by HACS ?

**Comment by ludeeus** [comment]
API routes?

**Comment by bokub** [comment]
> API routes?

What kind of information do you fetch from Github ?

Is it [`GET /repos/:owner/:repo` ](https://developer.github.com/v3/repos/#get)?

**Comment by ludeeus** [comment]
Oh Github endpoints.

There is a lot of endpoints in use, that also changes from version to version, I use whatever I need :D
`GET /repos/:owner/:repo` is one of them
I use <https://github.com/ludeeus/aiogithubapi> for most if not all calls.
