### ISSUE TITLE
15.10 not allowing to add integration

### ISSUE THREAD

**Issue by mf-social** [custom-components/hacs#728]
So, today I upgraded to 15.10 but something went screwy during the upgrade and when I rebooted homeassistant HACS wouldn't work giving the error "couldn't start HACS, check your configuration" with nothing more helpful in the logs.

So, I deleted the old configuration from configuration.yaml, deleted the old integration and the custom component/hacs folder - then rebooted.  I then downloaded and extracted the 15.10 hacs.zip, extracted it, put it back where it was supposed to be and rebooted.  No issues so far.

Then I went to integratons, click +, and click HACS - nothing happens - log states "Error occurred loading config flow for integration hacs: No module named 'custom_components.hacs.repositories.manifest'"

Presumption that this is the reason that the original upgrade didn't work.

## Version of HAC
15.10

## Describe the bug
Integration cannot be included

## Debug log
```text
Error occurred loading config flow for integration hacs: No module named 'custom_components.hacs.repositories.manifest'
```

**Comment by ludeeus** [comment]
You are missing at least one file (manifest.py)

**Comment by mf-social** [comment]
There is no manifest.py in the zip file - there is a manifest.json??

**Comment by ludeeus** [comment]
Would/should be under repositories/

**Comment by mf-social** [comment]
How bizarre - entire contents of repositories didn't copy over :/

Standby rebooting having re-copied everything one-by-one to be sure it's all gone!

**Comment by ludeeus** [comment]
Strange, how are you copying it?

**Comment by mf-social** [comment]
Drag and drop - windows explorer on the laptop > VSC addon on homeassistant - copied everything else, just failed to recursively do the repositories folder - that's a new one on me!!

OK that's done it 😃 

Will it automatically pick up that I have already got python_scripts, custom_components and appdaemon apps from a previous install at some point? Or should I go through and 're-add' them (even thought they're already there)?

**Comment by ludeeus** [comment]
If you did not remove files under .storage it will know it, if you did remove that you need to reinstall the elements

**Comment by mf-social** [comment]
OK - will have to re-add then as I removed everything to ensure 'clean' reinstall after the errors 😃 

Thanks for the prompt replies 👍
