### ISSUE TITLE
Add button BACK

### ISSUE THREAD

**Issue by pepeEL** [custom-components/hacs#73]
Hi
Good option feature request will be add button BACK. When we go to Store and then to module... when we want back to home we must click STORE., Good when will be add button BACK to come back to last view on store.

**Comment by ludeeus** [comment]
Your browser already have (or should have) a button for this, it's even in the expected place for it :)
![back](https://user-images.githubusercontent.com/15093472/59269862-4a19fc00-8c50-11e9-908c-1e577247f4ed.gif)
