### ISSUE TITLE
fix settings view for mobile view

### ISSUE THREAD

**Issue by royto** [custom-components/hacs#75]
## Version of HACS
0.6.0

## Describe the bug
Settings view is broken when used with phone screen 
![Screenshot_20190611-212826](https://user-images.githubusercontent.com/6990995/59300757-41e1b100-8c90-11e9-9fd8-6ba232d55335.jpg)

I primarily use my phone to manage my HA instance

**Comment by ludeeus** [comment]
Fixed in https://github.com/custom-components/hacs/releases/tag/0.7.0
