### ISSUE TITLE
Flag unused components

### ISSUE THREAD

**Issue by royto** [custom-components/hacs#76]
**Is your feature request related to a problem? Please describe.**
For maintenance point of view, it could be interesting to identify unused installed components (could be safely remove)
Also, it could be interesting to see the number of usage of a component (more about custom cards ...)

**Describe the solution you'd like**
Add an icon, text or number of use in the component view

**Comment by ludeeus** [comment]
I have looked into this.
It would be possible, but with how much different every user's config is, the risk of false negatives would be too high.

if implemented I would assume an issue like this at least once every week "HACS said I didn't use it, now my lovelace is broken"...

The level of development/testing/maintenance this would require does not make sense at this point.
Maybe in the future, but not now.
