### ISSUE TITLE
'X-Frame-Options' to 'deny'

### ISSUE THREAD

**Issue by phdelodder** [custom-components/hacs#87]
## Version of HACS

0.7.0

## Describe the bug
The Community page on the frontend doesn't load. 

Refused to display 'https://URL/community_2194ae62-b0c8-4774-a82f-4d6f1789cc6e-05a4c434-312e-4984-9356-a1b282691657' in a frame because it set 'X-Frame-Options' to 'deny'.

## Debug log

```text

component log removed
```

**Comment by ludeeus** [comment]
That header is not set by this component, it works just fine here.
This is the headers reported by [postman](https://www.getpostman.com/)

![image](https://user-images.githubusercontent.com/15093472/59517105-1abef580-8ec3-11e9-84ae-b2085431a00f.png)

Try a different browser and/or incognito mode.

**Comment by phdelodder** [comment]
I have tried firefox and chrome, even incognito can't get it working.

**Comment by ludeeus** [comment]
Can you paste a similar screenshot from your client?
![image](https://user-images.githubusercontent.com/15093472/59528002-6f6f6a00-8edd-11e9-863c-abbf88bf2014.png)

**Comment by phdelodder** [comment]
![image](https://user-images.githubusercontent.com/7259755/59554463-795ba080-8fa3-11e9-814c-aaecaf4d642a.png)

If I go to https://url/community_751d4493-72b6-443e-a5ab-378b72f9f4cb-a6edb994-01b8-477c-b30d-574befcf7202, it works. Note I use traefik as a proxy.

**Comment by ludeeus** [comment]
Then your proxy is doing something funky here.
in the list you have on your right there, find and mark "community" then upload a screenshot of that.

**Comment by phdelodder** [comment]
![image](https://user-images.githubusercontent.com/7259755/59554650-829a3c80-8fa6-11e9-9c20-a379f931c851.png)

**Comment by ludeeus** [comment]
Set `traefik.frontend.headers.frameDeny=false` in your Traefik config.
https://docs.traefik.io/configuration/backends/docker/

**Comment by mpeterson** [comment]
> Set `traefik.frontend.headers.frameDeny` in your Traefik config.
> https://docs.traefik.io/configuration/backends/docker/

Would be nice to have a not on the installation docs. It took me a long while to figure out (and only did after finding this issue)
