### ISSUE TITLE
alexa_media

### ISSUE THREAD

**Issue by ashepp** [custom-components/hacs#93]
## Debug log

```text

Add your logs here.

```

**Comment by ashepp** [comment]
Not a bug but a question. I don't understand how to integrate custom componenets I previously updated with custom_updater such as Alexa_media_player or https://github.com/moment/moment/ ? Is there a way to include in HACS or should I be using a different approach?

**Comment by ludeeus** [comment]
<https://github.com/moment/moment/> is not a component or a card, and cannot be added.

Alexa_media_player? probably <https://github.com/keatontaylor/alexa_media_player> it does not meet the requrements, and cannot be added ref <https://custom-components.github.io/hacs/#note-for-integration-developers>.

This will not support all that custom_updater did but will support more with less work for the dev.

**Comment by xatr0z** [comment]
https://github.com/keatontaylor/alexa_media_player will be working after my pull request is merged:
https://github.com/keatontaylor/alexa_media_player/issues/201
